In [1]:
import sys
import os
from timeit import default_timer as timer
os.getcwd()

'/home/jupyter/Notebooks/crystal/NLP/nlp_testing'

In [ ]:
# Adapted from the tutorial at https://mccormickml.com/2019/05/14/BERT-word-embeddings-tutorial/

In [2]:
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
#logging.basicConfig(level=logging.INFO)

import matplotlib.pyplot as plt
%matplotlib inline

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [7]:
# list(tokenizer.vocab.keys())[5000:5020]
list(tokenizer.vocab.keys())[17733]

'disgusted'

In [ ]:
# Define a new example sentence with multiple meanings of the word "disgusted"
text = "[CLS] She made a disgusted pout [SEP] Her disgusted expression was contagious [SEP]"

# Split the sentence into tokens.
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)

# Map the token strings to their vocabulary indeces.
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

# Display the words with their indeces.
for tup in zip(tokenized_text, indexed_tokens):
    print('{:<12} {:>6,}'.format(tup[0], tup[1]))

In [ ]:
# Recreate vocabulary words from their tokenized representations.
for t in tokenized_text:
    this_word = ''
    for token in t:
        this_word += token.strip('#')
#     print(this_word)

In [ ]:
# Mark each of the tokens as belonging to sentence "0" or "1".

segments_ids = [1] * len(tokenized_text[3])
# segments_ids = [0,0,0]
print (segments_ids)
print(indexed_tokens)
print(tokenized_text[3])

In [ ]:
# Convert inputs to PyTorch tensors
tokens_tensor = torch.tensor([indexed_tokens[3]])
segments_tensors = torch.tensor([segments_ids])

# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-uncased')

# Put the model in "evaluation" mode, meaning feed-forward operation.
model.eval()

In [ ]:
# Predict hidden states features for each layer
with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, segments_tensors)

In [ ]:
print ("Number of layers:", len(encoded_layers))
layer_i = 0

print ("Number of batches:", len(encoded_layers[layer_i]))
batch_i = 0

print ("Number of tokens:", len(encoded_layers[layer_i][batch_i]))
token_i = 1

print ("Number of hidden units:", len(encoded_layers[layer_i][batch_i][token_i]))

In [ ]:
# For our token, select its feature values from layer 5.
token_i = 1
layer_i = 5
vec = encoded_layers[layer_i][batch_i][token_i]
# print(vec)

# Plot the values as a histogram to show their distribution.
plt.figure(figsize=(10,10))
plt.hist(vec, bins=200)
plt.show()

In [ ]:
# `encoded_layers` is a Python list.
print('     Type of encoded_layers: ', type(encoded_layers))

# Each layer in the list is a torch tensor.
print('Tensor shape for each layer: ', encoded_layers[0].size())

In [ ]:
# Concatenate the tensors for all layers. We use `stack` here to
# create a new dimension in the tensor.
token_embeddings = torch.stack(encoded_layers, dim=0)

token_embeddings.size()

In [ ]:
# Remove dimension 1, the "batches".
token_embeddings = torch.squeeze(token_embeddings, dim=1)

token_embeddings.size()

In [ ]:
# Swap dimensions 0 and 1.
token_embeddings = token_embeddings.permute(1,0,2)

token_embeddings.size()

In [23]:
# Concatenate the last 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_last = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_last.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_last), len(token_vecs_cat_last[0])))
print(token_vecs_cat_last[0])

Shape is: 1 x 3072
tensor([-0.2373,  0.8259, -0.6190,  ..., -0.3836, -0.5039,  0.6153])


In [24]:
# Sum the last 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_last = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[-4:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_last.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_last), len(token_vecs_sum_last[0])))

Shape is: 1 x 768


In [ ]:
# Concatenate the first 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_first = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[0], token[1], token[2], token[3]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_first.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_first), len(token_vecs_cat_first[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the first 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_first = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[:4], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_first.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_first), len(token_vecs_sum_first[0])))

In [ ]:
# Concatenate the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_middle1 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[4], token[5], token[6], token[7]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_middle1.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_middle1), len(token_vecs_cat_middle1[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_middle1 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[4:8], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_middle1.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_middle1), len(token_vecs_sum_middle1[0])))

In [ ]:
# Concatenate the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_middle2 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[8], token[9], token[10], token[11]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_middle2.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_middle2), len(token_vecs_cat_middle2[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_middle2 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[8:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_middle2.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_middle2), len(token_vecs_sum_middle2[0])))

In [ ]:
# Concatenate all hidden layers to create word embeddings.
token_vecs_cat_all = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[0], token[1], token[2], token[3], token[4], token[5], token[6], token[7], token[8], token[9], token[10], token[11]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_all.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_all), len(token_vecs_cat_all[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum all hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_all = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_all.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_all), len(token_vecs_sum_all[0])))

In [ ]:
# Make a single vector to represent the pair of sentences by averaging across tokens.
# `encoded_layers` has shape [12 x 1 x 22 x 768]
sentences_vec = []
# `token_vecs` is a tensor with shape [22 x 768]
token_vecs = encoded_layers[11][0]

# Calculate the average of all 22 token vectors.
sentence_embedding = torch.mean(token_vecs, dim=0)
for s in sentence_embedding:
    sentences_vec.append(s)
print ("Our final sentence embedding vector of shape:", sentence_embedding.size())
print(sentence_embedding[767])
print(sentence_embedding[-1])
print(f'Shape of sentences vector is: {len(sentences_vec)}')
print(sentences_vec[-1])

In [ ]:
from scipy.spatial.distance import cosine
# Test the similarity of a word with itself.
# For words trained contextually, self-synonymy is less than 1.
similarity = 1 - cosine(token_vecs_cat[0], token_vecs_cat[0])
print(f'Similarity of {tokenized_text[8]} and {tokenized_text[8]} in token_vecs_cat is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum[4], token_vecs_sum[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_first[4], token_vecs_cat_first[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_first is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_first[4], token_vecs_sum_first[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_first is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_middle1[4], token_vecs_cat_middle1[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_middle1 is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_middle1[4], token_vecs_sum_middle1[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_middle1 is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_middle2[4], token_vecs_cat_middle2[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_middle2 is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_middle2[4], token_vecs_sum_middle2[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_middle2 is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_all[4], token_vecs_cat_all[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_all is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_all[4], token_vecs_sum_all[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_all is: {similarity}')

In [10]:
######################################################################################
############## BEGIN TESTING STATIC CONTEXTUAL EMBEDDING CREATION ####################
######################################################################################

In [11]:
def make_vocab(vocab_file):
    # start = timer()
    vocab = []
    # vocab_file = '/home/jupyter/Notebooks/crystal/NLP/MiFace/Python/vocab_files/vocab_checked.txt'
    with open(vocab_file, 'r') as v:
        vocab = v.read().splitlines()
    # end = timer()
    # run_time = end - start
#     print(f'There are {len(vocab)} words in the vocabulary.\n')
#     print(f'It took {run_time} seconds to read the vocabulary file into memory.')
#     print(f'Test word is {vocab[2]}.')
    return vocab

In [12]:
def tokenize_text(vocab):
    tokenized_text = []
    indexed_tokens = []
    for word in vocab:
        # Add the special tokens.
    #     marked_text = "[CLS] " + word + " [SEP]"
        marked_text = word

        # Split the sentence into tokens.
        # tokenized_text = tokenizer.tokenize(marked_text)
        tokenized_text.append(tokenizer.tokenize(marked_text))
#         print(f'Added {tokenized_text[-1]} to the tokenized_text array.')


        # Map the token strings to their vocabulary indeces.
        indexed_tokens.append(tokenizer.convert_tokens_to_ids(tokenized_text[-1]))

        # Display the words with their indeces.
    #     print(f'The word {tokenized_text[-1][1]} is at index {indexed_tokens[-1]}.')
#         for tup in zip(tokenized_text[-1], indexed_tokens[-1]):
#             print('{:<12} {:>6,}'.format(tup[0], tup[1]))
    return tokenized_text, indexed_tokens

In [13]:
def generate_segments_IDs(tokenized_text):
    # Create segment IDs for sentence 1 (there can be a sentence 0 to compare to
    # sentence 1, but we're not doing that).
    # Check that indices and token indices look correct.
    segments_IDs = []
    for i in range(len(tokenized_text)):
        segments_IDs.append([1] * len(tokenized_text[i]))
#     for i in range(len(segments_IDs)):
#         print (segments_IDs[i])
#         print(tokenized_text[i])
    return segments_IDs

In [14]:
def generate_embeddings(indexed_tokens, segments_IDs):
    # Convert inputs to PyTorch tensors
    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_IDs])

    # Load pre-trained model (weights)
    model = BertModel.from_pretrained('bert-base-uncased')

    # Put the model in "evaluation" mode, meaning feed-forward operation.
    model.eval()

    # Predict hidden states features for each layer
    with torch.no_grad():
        encoded_layers, _ = model(tokens_tensor, segments_tensors)
#         print('Type of encoded_layers: ', type(encoded_layers))
        # Each layer in the list is a torch tensor.
#         print('Tensor shape for each layer: ', encoded_layers[0].size())

    # Concatenate the tensors for all layers. We use `stack` here to
    # create a new dimension in the tensor.
    token_embeddings = torch.stack(encoded_layers, dim=0)
#     print(token_embeddings.size())

    # Remove dimension 1, the "batches".
    token_embeddings = torch.squeeze(token_embeddings, dim=1)
#     print(token_embeddings.size())

    # Swap dimensions 0 and 1.
    token_embeddings = token_embeddings.permute(1,0,2)
#     print(token_embeddings.size())
    
    return token_embeddings

In [15]:
def cat_last_four(token_embeddings): 
    # Concatenate the last 4 hidden layers to create contextual embeddings.
    # Stores the token vectors, with shape [22 x 3,072]
    token_vecs_cat_last = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_last.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_last), len(token_vecs_cat_last[0])))
    print(token_vecs_cat_last[0])
    
    return token_vecs_cat_last

In [16]:
def cat_middle_four1(token_embeddings):
    # Concatenate the middle 4 hidden layers to create word embeddings.
    # Stores the token vectors, with shape [22 x 3,072]
    token_vecs_cat_middle1 = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last 
        # four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[4], token[5], token[6], token[7]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_middle1.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_middle1), len(token_vecs_cat_middle1[0])))
    print(token_vecs_cat_middle1[0])
    
    return token_vecs_cat_middle1

In [17]:
def cat_first_four(token_embeddings):
    token_vecs_cat_first = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last 
        # four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[0], token[1], token[2], token[3]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_first.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_first), len(token_vecs_cat_first[0])))
    print(token_vecs_cat_first[0])
    
    return token_vecs_cat_first

In [18]:
def get_mean_embedding(token_embeddings):
    mean_embedding = sum(token_embeddings) / len(token_embeddings)
    print(mean_embedding)
    
    return mean_embedding

In [19]:
def reconstruct_tokens(tokenized_text):
    vocab_word = ''
    for i in tokenized_text:
        vocab_word += i.strip('#')
    print(vocab_word)

    return vocab_word

In [20]:
def write_embedding(embeddings_file, vocab_word, contextual_embedding):
    try:
        with open(embeddings_file, 'a') as f:
            f.write(vocab_word)
            for value in contextual_embedding[0]:
                f.write(' ' + str(value.item()))
            f.write('\n')
        print(f'Saved the embedding for {vocab_word}.')
    except:
        print('Oh no! Unable to write to the embeddings file.')

In [23]:
# if __name__ == "__main__":
# Set up input and output paths.
vocab_file = '/home/jupyter/Notebooks/crystal/NLP/MiFace/Python/vocab_files/vocab_checked.txt'
layer_combining_function = cat_middle_four1
embeddings_file = os.path.join('/home/jupyter/Notebooks/crystal/NLP/nlp_testing/embeddings_context_vocab', layer_combining_function.__name__ + '.txt')
if os.path.exists(embeddings_file):
    os.remove(embeddings_file)

    # Create a list of vocabulary words we want embeddings for.
vocab = make_vocab(vocab_file)

# Tokenize the vocabulary and look up the BERT token indices.
tokenized_text, indexed_tokens = tokenize_text(vocab)

# Generate segment IDs for each token.
segments_IDs = generate_segments_IDs(tokenized_text)

# Generate and write out the contextual embeddings for the vocabulary words.
# Embeddings are saved in a standard format that can be used for calcualting
# the cosine distances between word vectors.
for i in range(len(tokenized_text)):
    # Convert indexed tokens and segments to tensors.
    # Create a BERT model for the tokens.
    # Get the encoded model layers and reshape them.
    token_embeddings = generate_embeddings(indexed_tokens[i], segments_IDs[i])
    print(f'{tokenized_text[i]} has a token embedding of size {token_embeddings.size()}')

    # Extract the contextual embedding for a token.
    contextual_embedding = layer_combining_function(token_embeddings)

    # Write the embedding to a text file, with the vocabulary word prepended.
    vocab_word = reconstruct_tokens(tokenized_text[i])
    # Make sure we've got the correct vocabulary word.
    assert vocab[i] == vocab_word
    write_embedding(embeddings_file, vocab[i], contextual_embedding)

['aback'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3298,  0.4090, -0.5590,  ..., -0.3376, -0.3176,  0.0872])
aback
Saved the embedding for aback.
['aba', '##shed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1815,  0.2656, -0.7644,  ..., -1.2575, -1.1458,  0.3598])
abashed
Saved the embedding for abashed.
['ab', '##hor'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0624, -0.0087,  0.2358,  ..., -0.8970, -0.5811,  0.3655])
abhor
Saved the embedding for abhor.
['ab', '##hor', '##red'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1223, -0.0474, -0.1086,  ..., -0.7768, -0.3913,  0.2025])
abhorred
Saved the embedding for abhorred.
['ab', '##hor', '##rence'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2506,  0.1359, -0.1205,  ..., -1.0102, -0.0365,  0.6184])
abhorrence
Saved the embedding 

['ag', '##gra', '##vation'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.1651,  0.7620,  0.1863,  ...,  0.1485,  0.2556, -0.3368])
aggravation
Saved the embedding for aggravation.
['aggression'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5449,  0.5502,  0.2965,  ..., -0.6756, -0.8149, -0.6476])
aggression
Saved the embedding for aggression.
['aggressive'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2159,  0.4010,  0.4523,  ..., -0.0068, -0.6904, -0.1985])
aggressive
Saved the embedding for aggressive.
['ag', '##gr', '##ie', '##ve'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.2395,  0.8428,  0.0794,  ..., -0.5343,  0.2387,  0.1088])
aggrieve
Saved the embedding for aggrieve.
['ag', '##gr', '##ie', '##ved'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.1582,  0.8501,  0.0612,  ..., -1.126

['ang', '##st'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0919, -0.0538,  0.7924,  ..., -0.5212, -0.3995,  0.1277])
angst
Saved the embedding for angst.
['anguish'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1329, -0.1217, -0.2044,  ..., -0.4078,  0.4993, -0.6908])
anguish
Saved the embedding for anguish.
['anguish', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1667, -0.0780,  0.1563,  ..., -0.0180,  0.2595, -0.5629])
anguished
Saved the embedding for anguished.
['animated'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1417, -0.8973, -0.4974,  ..., -0.0671, -0.4695,  0.0209])
animated
Saved the embedding for animated.
['an', '##imo', '##sity'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.1243,  0.7214,  0.0455,  ..., -0.5057, -0.8948,  1.1199])
animosity
Saved the embedding fo

['ashamed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2217, -0.0502,  0.2985,  ..., -0.5433, -0.9641, -0.2594])
ashamed
Saved the embedding for ashamed.
['aspiring'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1903,  0.1534,  0.5512,  ..., -0.1296, -1.0976, -0.0734])
aspiring
Saved the embedding for aspiring.
['assert', '##ive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0207,  0.3628,  0.3114,  ..., -0.4476, -1.1078, -0.6858])
assertive
Saved the embedding for assertive.
['assert', '##ively'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1240,  0.4932,  0.0686,  ..., -0.3355, -0.7104, -1.1085])
assertively
Saved the embedding for assertively.
['assessing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1840,  0.0447, -0.1364,  ..., -0.6361, -0.2406,  0.4616])
assessing
Saved the embedd

['beat'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3468,  0.3886,  0.4718,  ...,  0.2080,  0.0875, -0.1007])
beat
Saved the embedding for beat.
['beaten'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0346,  0.1107, -0.1936,  ...,  0.3533, -0.3622,  0.0366])
beaten
Saved the embedding for beaten.
['bed', '##ev', '##iled'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2118,  0.1441,  0.0653,  ..., -0.0241, -0.5221, -0.1654])
bedeviled
Saved the embedding for bedeviled.
['be', '##fu', '##ddled'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.3803, -0.2611, -0.2467,  ..., -0.4744, -0.3737,  0.0625])
befuddled
Saved the embedding for befuddled.
['begging'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3503,  0.8269,  0.5973,  ...,  0.5078, -0.0924, -0.7290])
begging
Saved the embedding for beggi

['bleak'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4399, -0.3844, -0.1213,  ..., -1.1919, -0.0960,  0.2951])
bleak
Saved the embedding for bleak.
['b', '##lea', '##ry'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2619, -0.0184,  0.2907,  ..., -0.8140, -0.9146, -0.0279])
bleary
Saved the embedding for bleary.
['blessed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1679,  1.3999,  0.3925,  ..., -0.3641,  0.0469,  0.1279])
blessed
Saved the embedding for blessed.
['blew'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3698, -0.2978, -0.9332,  ..., -0.1053, -0.4458, -0.1950])
blew
Saved the embedding for blew.
['blinded'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0269,  0.3349, -0.3795,  ...,  0.6970,  0.0298,  0.0093])
blinded
Saved the embedding for blinded.
['blinds', '##ided'] has a

['bully'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5327,  0.7858,  0.1503,  ...,  0.8557, -0.9734, -0.7696])
bully
Saved the embedding for bully.
['bullying'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8483,  0.2726,  0.2430,  ...,  0.2717, -1.3924, -1.2614])
bullying
Saved the embedding for bullying.
['bum', '##med'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.6281,  0.2373, -0.2239,  ..., -0.2081, -0.4644,  0.3086])
bummed
Saved the embedding for bummed.
['bu', '##oya', '##nt'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.0402,  0.0630,  0.7273,  ..., -1.2395, -0.0301,  0.9115])
buoyant
Saved the embedding for buoyant.
['burden', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.3478, -0.4301,  0.1586,  ..., -0.5697, -0.3919, -0.0998])
burdened
Saved the embedding for burdened.

['challenged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2603,  0.0813,  0.7254,  ..., -0.8205, -1.4512,  0.2784])
challenged
Saved the embedding for challenged.
['challenging'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0730,  0.3807,  1.2924,  ..., -0.1164, -0.8546, -0.0895])
challenging
Saved the embedding for challenging.
['chaotic'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8538,  0.3801,  0.0631,  ..., -0.9652, -0.3289, -0.0336])
chaotic
Saved the embedding for chaotic.
['charged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.7537,  0.3778, -0.0160,  ...,  0.5611,  0.8080,  0.5534])
charged
Saved the embedding for charged.
['charm', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.8889, -0.3732, -0.3213,  ..., -0.7489, -0.2160, -0.4076])
charmed
Saved the embedding for ch

['clue', '##less'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3378,  0.1192,  0.3622,  ..., -0.5830, -0.9037,  0.3990])
clueless
Saved the embedding for clueless.
['clutched'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5151,  0.0657, -0.4591,  ..., -0.1292, -0.8105,  0.0264])
clutched
Saved the embedding for clutched.
['cl', '##uttered'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.3183, -0.4592,  0.3346,  ..., -0.8507, -0.7320, -0.6789])
cluttered
Saved the embedding for cluttered.
['cock', '##eye', '##d'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.5425,  0.3553,  0.2213,  ...,  0.2495, -0.2981, -0.3728])
cockeyed
Saved the embedding for cockeyed.
['cock', '##iness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0731,  0.5986,  0.9266,  ..., -0.0702, -1.2590,  0.7583])
cockiness
Save

['concentration'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 1.0188,  1.6752, -0.1792,  ..., -0.0436, -0.0198,  0.1528])
concentration
Saved the embedding for concentration.
['concern'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1071,  0.9430,  0.2099,  ...,  0.1873, -0.7079,  0.0045])
concern
Saved the embedding for concern.
['concerned'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4832,  1.3301,  0.2816,  ...,  0.6450, -0.2615, -0.3618])
concerned
Saved the embedding for concerned.
['con', '##ci', '##lia', '##tory'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.1205, -0.2932, -0.0601,  ..., -0.1939, -0.5387,  0.9987])
conciliatory
Saved the embedding for conciliatory.
['con', '##clusive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4019,  0.3343,  0.2059,  ...,  0.3427, -1.2563,  0.71

['content'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 1.1413,  0.7672,  0.3045,  ..., -0.0193,  0.0350,  0.3606])
content
Saved the embedding for content.
['content', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.8337,  0.5967,  0.1751,  ..., -0.1295, -0.0537,  0.3823])
contented
Saved the embedding for contented.
['contentious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2194,  0.4908, -0.1427,  ..., -0.7064, -1.1856, -0.8028])
contentious
Saved the embedding for contentious.
['content', '##ly'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.8588,  0.9086,  0.7389,  ..., -0.9285, -0.7225,  0.2137])
contently
Saved the embedding for contently.
['content', '##ment'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.8610,  0.6848,  0.5005,  ..., -0.0501,  0.0319,  0.4384])
contentment
Sav

['curiosity'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0260,  0.4663,  0.1062,  ..., -0.2582, -0.4133,  0.1888])
curiosity
Saved the embedding for curiosity.
['curious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3915,  0.5542, -0.2298,  ..., -0.2876, -0.0526, -0.4310])
curious
Saved the embedding for curious.
['cutting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0116, -0.5079,  0.6580,  ...,  0.8731, -0.4706, -0.1316])
cutting
Saved the embedding for cutting.
['cy', '##nic'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.8576,  0.0209,  0.1143,  ..., -0.4855, -0.7006,  0.5070])
cynic
Saved the embedding for cynic.
['cynical'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3641,  0.2279,  0.8325,  ..., -0.3694, -0.3807, -0.5860])
cynical
Saved the embedding for cynical.
['cy', '##nic'

['del', '##ibe', '##rating'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0467,  0.5301,  0.1428,  ..., -1.0922, -0.6665,  0.4631])
deliberating
Saved the embedding for deliberating.
['delight'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3881,  0.7654, -0.0803,  ..., -0.1026, -0.0562, -0.1091])
delight
Saved the embedding for delight.
['delighted'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0511,  0.3958,  0.3848,  ..., -0.5845, -0.9858,  0.1364])
delighted
Saved the embedding for delighted.
['delightful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.4578,  0.0725,  0.2304,  ..., -0.5234, -0.6216,  0.6086])
delightful
Saved the embedding for delightful.
['del', '##iri', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.3033,  0.3092, -0.4302,  ..., -1.0609, -0.2014,  0.4564])
delir

Saved the embedding for detached.
['determination'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.7843,  1.0054,  0.1698,  ..., -0.4316, -0.3155, -0.0524])
determination
Saved the embedding for determination.
['determined'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3260,  0.5767,  0.6342,  ..., -1.8545, -0.5249, -0.2131])
determined
Saved the embedding for determined.
['determining'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2251,  0.3140,  0.4599,  ..., -1.3758, -0.6726,  0.3906])
determining
Saved the embedding for determining.
['deter', '##red'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4679,  0.8405,  0.0123,  ..., -0.8547, -1.1477,  0.2733])
deterred
Saved the embedding for deterred.
['det', '##est'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1119,  0.3799, -0.5378,  ..., -0

['discount', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.6870, -0.2808,  0.2275,  ..., -0.7159, -0.7378, -0.3773])
discounted
Saved the embedding for discounted.
['discouraged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6556, -0.0557, -0.0534,  ...,  0.0797, -0.8085, -0.3167])
discouraged
Saved the embedding for discouraged.
['discovery'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2440, -0.2262,  0.0570,  ...,  0.3216, -0.8525,  0.2160])
discovery
Saved the embedding for discovery.
['disc', '##rim', '##inating'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1812,  0.5229, -0.5024,  ..., -0.7321,  0.1689,  0.7420])
discriminating
Saved the embedding for discriminating.
['discussed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3958, -0.0018,  0.1367,  ..., -0.5279, -0.6644, -0.

['di', '##sp', '##ass', '##ion', '##ate'] has a token embedding of size torch.Size([5, 12, 768])
Shape is: 5 x 3072
tensor([ 0.0395,  0.2929,  0.0902,  ...,  0.5661, -0.4155,  0.8880])
dispassionate
Saved the embedding for dispassionate.
['di', '##sp', '##iri', '##ted'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.3214,  0.0795, -0.5101,  ..., -0.3486, -0.3124,  0.5629])
dispirited
Saved the embedding for dispirited.
['di', '##sp', '##iri', '##ted', '##ness'] has a token embedding of size torch.Size([5, 12, 768])
Shape is: 5 x 3072
tensor([-0.1573,  0.1145, -0.2657,  ..., -0.3661, -0.2659,  1.1185])
dispiritedness
Saved the embedding for dispiritedness.
['di', '##sp', '##lea', '##sed'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.0863, -0.0326,  0.0566,  ..., -0.3708, -0.3891,  0.1196])
displeased
Saved the embedding for displeased.
['displeasure'] has a token embedding of size torch.Size([1, 12, 768])
Shap

['do', '##pe', '##y'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2886, -0.0036, -1.1624,  ..., -0.2556,  0.1008,  0.7322])
dopey
Saved the embedding for dopey.
['dot', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4754,  0.0516, -0.8333,  ..., -0.4947, -0.1900, -0.1857])
doting
Saved the embedding for doting.
['doubt'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1681,  0.3056,  0.2218,  ..., -0.9208, -0.8872,  0.3164])
doubt
Saved the embedding for doubt.
['doubt', '##er'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.5449,  0.4106,  0.2355,  ..., -1.6421, -0.6299,  0.3549])
doubter
Saved the embedding for doubter.
['doubtful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5290, -0.0093,  0.0561,  ...,  0.0789, -0.4798, -0.2905])
doubtful
Saved the embedding for doubtful.
['doubtf

['eager'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6368,  0.6383,  0.4946,  ..., -0.3456, -0.5453, -0.2687])
eager
Saved the embedding for eager.
['eager', '##ness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1254,  0.4464,  0.4982,  ..., -0.6493, -0.8224,  0.0136])
eagerness
Saved the embedding for eagerness.
['earnest'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4530,  0.8569,  0.2034,  ..., -0.6237, -0.2755, -0.1975])
earnest
Saved the embedding for earnest.
['easy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1076, -0.0028,  0.4765,  ...,  0.2620, -0.3975,  0.0949])
easy
Saved the embedding for easy.
['e', '##bu', '##llie', '##nt'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.5499, -0.0541, -0.1461,  ..., -0.3321, -0.3411,  0.3621])
ebullient
Saved the embedding for ebullient.

['eng', '##ross', '##ed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1102,  0.2332, -0.5452,  ..., -0.3526, -0.4899,  0.6991])
engrossed
Saved the embedding for engrossed.
['eng', '##ross', '##ment'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0360,  0.4183, -0.4674,  ...,  0.0159,  0.0543,  0.8158])
engrossment
Saved the embedding for engrossment.
['enigma', '##tic'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.6274,  0.7620,  0.2764,  ..., -0.3871, -0.3221, -0.1838])
enigmatic
Saved the embedding for enigmatic.
['enjoy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0036,  0.1937,  0.8522,  ..., -1.0339, -0.4508, -0.7457])
enjoy
Saved the embedding for enjoy.
['enjoying'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1645,  0.7945,  0.3872,  ..., -0.1155,  0.1368, -0.7387])
enjoying
Sav

Saved the embedding for exclamatory.
['exhausted'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1804, -0.2645, -0.2613,  ...,  0.2504, -0.7891, -0.2675])
exhausted
Saved the embedding for exhausted.
['exhaustion'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0488, -0.2125, -0.7826,  ..., -0.2741, -0.4550,  0.3178])
exhaustion
Saved the embedding for exhaustion.
['exhaust', '##ive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1645, -0.6185, -0.3525,  ..., -0.6509, -0.1731, -0.7790])
exhaustive
Saved the embedding for exhaustive.
['ex', '##hila', '##rated'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1079, -0.1116,  0.6021,  ..., -0.6616, -0.2394,  0.3647])
exhilarated
Saved the embedding for exhilarated.
['ex', '##hila', '##ration'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1375, -0.03

tensor([ 0.1673,  0.6717,  0.3453,  ...,  0.1252, -0.9906, -0.2115])
fear
Saved the embedding for fear.
['feared'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1415,  0.4654,  0.9874,  ..., -0.5411, -0.6040, -0.3832])
feared
Saved the embedding for feared.
['fearful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2111,  0.2667,  0.4619,  ..., -0.4575, -0.8493,  0.0567])
fearful
Saved the embedding for fearful.
['fearing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0218,  0.5108,  0.4832,  ..., -0.6564, -1.0610, -0.0852])
fearing
Saved the embedding for fearing.
['fearless'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2295,  0.1290,  0.6818,  ...,  0.0683, -0.3687,  0.3013])
fearless
Saved the embedding for fearless.
['fears', '##ome'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1652,  0

Saved the embedding for foiled.
['foolish'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4577,  0.4468,  0.2078,  ...,  0.5730, -0.2981, -0.6793])
foolish
Saved the embedding for foolish.
['for', '##be', '##aring'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.3498,  0.3516,  0.5257,  ..., -1.1977, -0.7480,  0.3929])
forbearing
Saved the embedding for forbearing.
['forbid', '##ding'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.5441,  0.0873, -0.3038,  ..., -0.6322, -1.0997,  0.8923])
forbidding
Saved the embedding for forbidding.
['forced'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1411,  0.0068, -0.0403,  ..., -0.5266, -0.3567, -0.1449])
forced
Saved the embedding for forced.
['forceful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5771,  0.2690,  0.4058,  ..., -0.3871, -0.8267, -0.68

tensor([-0.0014,  0.4900,  0.5861,  ..., -0.6051, -0.8898, -0.0982])
furiousness
Saved the embedding for furiousness.
['furrowed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0914,  0.6159, -0.3188,  ...,  0.1775, -0.8807, -0.1411])
furrowed
Saved the embedding for furrowed.
['fur', '##tive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 1.3175,  0.0549, -0.3583,  ..., -0.1895, -0.7998, -0.2307])
furtive
Saved the embedding for furtive.
['fury'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1949,  1.0272,  0.5878,  ...,  0.6209, -0.4646,  0.2646])
fury
Saved the embedding for fury.
['fuss', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0030,  0.6034, -0.2090,  ..., -0.7710, -0.9754,  0.7929])
fussy
Saved the embedding for fussy.
['gall', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor(

['grand', '##ios', '##e'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1948,  0.1671, -0.3199,  ..., -0.9076, -0.4265, -0.4202])
grandiose
Saved the embedding for grandiose.
['grateful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0537,  0.2159,  0.1231,  ..., -0.3781, -0.9277,  0.0168])
grateful
Saved the embedding for grateful.
['gr', '##ati', '##fied'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.4331,  0.3317,  0.0547,  ..., -0.8302, -0.0899,  0.1982])
gratified
Saved the embedding for gratified.
['grave'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5372,  0.4498,  1.1044,  ..., -0.0295, -0.6849, -0.2153])
grave
Saved the embedding for grave.
['great'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3993,  0.5754,  0.6903,  ..., -0.4586, -0.4790,  0.5805])
great
Saved the embedding for 

['harsh'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0160,  0.3555,  0.5828,  ..., -0.5847, -0.9461,  0.4166])
harsh
Saved the embedding for harsh.
['hate'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4766,  0.4677,  0.0235,  ..., -0.3260, -0.8997, -0.5799])
hate
Saved the embedding for hate.
['hate', '##ful'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4743,  0.4472, -0.2136,  ..., -1.2979, -0.9517, -0.3469])
hateful
Saved the embedding for hateful.
['hating'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2491,  0.3186, -0.0459,  ..., -0.3127, -0.2251, -0.6733])
hating
Saved the embedding for hating.
['hatred'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3547,  0.6880,  0.0952,  ...,  0.0828, -0.1843,  0.2075])
hatred
Saved the embedding for hatred.
['ha', '##ught', '##y'] has a token

['hostility'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3324,  0.4256,  0.0864,  ..., -0.6426, -0.9671,  0.0702])
hostility
Saved the embedding for hostility.
['hot'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0822,  0.4994,  0.3051,  ...,  0.4011,  0.3865, -0.5241])
hot
Saved the embedding for hot.
['hot', '##shot'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2833, -0.3765,  0.3147,  ...,  0.2540, -0.0717,  0.3343])
hotshot
Saved the embedding for hotshot.
['huff', '##iness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5318,  0.6589,  0.5174,  ..., -1.2567, -0.8081,  0.4129])
huffiness
Saved the embedding for huffiness.
['huff', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5812,  0.5229,  0.0406,  ..., -0.6793, -0.1727, -0.0469])
huffy
Saved the embedding for huffy.
['humble

['imp', '##eri', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.4961, -0.1650,  1.1762,  ..., -0.7587, -0.1341, -0.2666])
imperious
Saved the embedding for imperious.
['imp', '##erson', '##al'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.6640, -0.5208,  0.5667,  ...,  0.0109, -0.2720,  0.0873])
impersonal
Saved the embedding for impersonal.
['imp', '##ert', '##inen', '##t'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.0065, -0.2487,  0.6225,  ..., -1.0823, -0.1917,  0.0641])
impertinent
Saved the embedding for impertinent.
['imp', '##ish'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 3.3578e-04, -3.6638e-01,  9.1053e-01,  ...,  3.9484e-02,
        -2.9258e-01,  1.2628e-01])
impish
Saved the embedding for impish.
['implicated'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4064, -0.379

['in', '##fl', '##ame', '##d'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.1280, -0.2611, -0.5078,  ..., -0.3981,  0.1285, -0.0436])
inflamed
Saved the embedding for inflamed.
['informal'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0705,  0.2588, -0.5947,  ..., -0.9175, -0.8820,  0.4459])
informal
Saved the embedding for informal.
['informing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.9433,  0.7942,  0.7381,  ..., -1.0194, -0.4618, -0.1002])
informing
Saved the embedding for informing.
['in', '##fur', '##iated'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2585, -0.0659,  0.5493,  ..., -1.6056,  0.0327,  0.3747])
infuriated
Saved the embedding for infuriated.
['inhibit', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0702,  0.2004, -0.1079,  ..., -0.2670, -1.1686,  0.3664])
in

['interacting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5653,  0.5284,  0.2661,  ..., -0.3479, -0.2889, -0.8289])
interacting
Saved the embedding for interacting.
['interest'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2915,  1.0307,  0.0777,  ...,  1.4320, -1.0794, -0.5132])
interest
Saved the embedding for interest.
['interested'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1165,  0.9277,  0.4718,  ...,  0.6607, -0.9263, -0.5157])
interested
Saved the embedding for interested.
['inter', '##ject', '##ing'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0531,  0.3989, -0.0243,  ..., -1.0493, -0.1389, -0.0261])
interjecting
Saved the embedding for interjecting.
['internal', '##izing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.8263,  0.1699,  0.1535,  ..., -1.6444, -1.1420, -0.1601]

['jealous'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2804,  0.4477,  0.0273,  ...,  0.4621, -0.2881,  0.1454])
jealous
Saved the embedding for jealous.
['je', '##ering'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3740,  0.2051, -1.0138,  ...,  0.0084,  0.2328,  0.7492])
jeering
Saved the embedding for jeering.
['je', '##sti', '##ng'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.4978,  0.1962, -0.3347,  ..., -0.0518,  0.0036,  0.4491])
jesting
Saved the embedding for jesting.
['ji', '##lt', '##ed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.4654, -0.1867, -0.7257,  ..., -0.9153, -1.1995,  0.5948])
jilted
Saved the embedding for jilted.
['ji', '##tter', '##y'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1323,  0.1583, -0.5876,  ..., -0.3573, -0.2638,  0.2115])
jittery
Saved the embe

['laughter'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1718,  0.1534, -0.2944,  ..., -0.6027, -0.3239,  0.4660])
laughter
Saved the embedding for laughter.
['lazy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1624,  1.3352, -0.0448,  ..., -0.2263, -0.2032,  0.6231])
lazy
Saved the embedding for lazy.
['leaving'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4892,  0.1696,  0.1829,  ...,  1.1452, -0.8735, -0.5866])
leaving
Saved the embedding for leaving.
['le', '##cher', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.7797,  0.0332, -0.3809,  ...,  0.2339, -0.1752, -0.1155])
lecherous
Saved the embedding for lecherous.
['le', '##cturing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1425, -0.3282, -0.5656,  ..., -0.0834, -0.3856,  0.5180])
lecturing
Saved the embedding for lecturi

['lying'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0229,  0.7143, -0.1414,  ...,  0.5851,  0.2836, -0.4342])
lying
Saved the embedding for lying.
['mad'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0988,  0.6161,  0.3298,  ..., -0.6297, -0.3663, -0.0365])
mad
Saved the embedding for mad.
['madden', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-1.0955, -0.5860, -0.4872,  ..., -0.0458, -0.4508,  0.3686])
maddened
Saved the embedding for maddened.
['madness'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4387, -0.2444,  0.1812,  ..., -0.6731, -0.6414,  0.5440])
madness
Saved the embedding for madness.
['mal', '##con', '##ten', '##t'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.6905, -0.3561, -0.5045,  ..., -0.5386, -0.2964,  0.6761])
malcontent
Saved the embedding for malcontent.
['

['mis', '##giving'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1486,  0.2985, -0.8108,  ...,  0.0638,  0.1832,  0.3438])
misgiving
Saved the embedding for misgiving.
['mis', '##lea', '##d'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2967,  0.0209, -0.5250,  ..., -0.5025, -0.0024,  0.2638])
mislead
Saved the embedding for mislead.
['mist', '##rus', '##t'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.5533,  0.5415, -0.0498,  ..., -0.1732, -0.5620,  0.3139])
mistrust
Saved the embedding for mistrust.
['mist', '##rus', '##tf', '##ul'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.4406,  0.5743, -0.0846,  ..., -0.1635, -0.1341,  0.2649])
mistrustful
Saved the embedding for mistrustful.
['mist', '##rus', '##ting'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.6999,  0.7680,  0.2958,  ...,  0.1

['nausea'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0843,  0.5707,  0.7484,  ..., -1.3576, -0.9315,  0.4976])
nausea
Saved the embedding for nausea.
['nausea', '##ted'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1417,  0.5234,  0.2608,  ..., -1.5976, -1.4198,  0.4095])
nauseated
Saved the embedding for nauseated.
['na', '##use', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2890,  0.0388, -0.2285,  ..., -0.7129, -0.4439,  0.8379])
nauseous
Saved the embedding for nauseous.
['needy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6276,  0.8658,  0.5791,  ..., -0.7478, -0.6379, -0.2796])
needy
Saved the embedding for needy.
['ne', '##far', '##ious'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1289,  0.0049,  0.0759,  ..., -0.8566, -0.0093, -0.2501])
nefarious
Saved the embedding

['ob', '##ser', '##vant'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0278,  0.1275, -0.5911,  ..., -0.1768,  0.0661,  0.4063])
observant
Saved the embedding for observant.
['observing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4261,  0.8198,  0.2474,  ...,  0.1001,  0.8190, -0.2577])
observing
Saved the embedding for observing.
['obsessed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3643, -0.0733,  0.9175,  ..., -0.6175, -0.4773, -0.8750])
obsessed
Saved the embedding for obsessed.
['ob', '##sti', '##nate'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2430,  0.2623, -0.3482,  ..., -0.8847, -0.6419,  0.4363])
obstinate
Saved the embedding for obstinate.
['occupied'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4557,  0.5894, -0.0432,  ..., -0.4301, -0.9943, -0.2437])
occupied
Saved 

['pained'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1408, -0.0573, -0.7228,  ..., -0.5580,  0.1712, -0.4631])
pained
Saved the embedding for pained.
['painful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1000, -0.0625,  0.1629,  ...,  0.1689, -0.6947,  0.0955])
painful
Saved the embedding for painful.
['painfully'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2259,  0.1839,  1.0978,  ..., -0.4918, -0.0920, -0.9088])
painfully
Saved the embedding for painfully.
['panic'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3428,  0.4048, -0.3584,  ...,  0.0702, -1.0125,  0.5610])
panic
Saved the embedding for panic.
['panicked'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1056, -0.1386,  0.0266,  ...,  0.1332, -0.0201, -0.4966])
panicked
Saved the embedding for panicked.
['panic', '##ky'] ha

['pinched'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1917,  0.4420, -0.9684,  ...,  0.2475, -0.3644, -0.1377])
pinched
Saved the embedding for pinched.
['pious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2322, -0.0637,  0.9110,  ..., -0.1279, -1.1780, -0.0300])
pious
Saved the embedding for pious.
['pi', '##que', '##d'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0327, -0.1452, -0.6025,  ..., -0.7176, -0.5692,  1.3150])
piqued
Saved the embedding for piqued.
['pissed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0566,  0.2042,  0.9819,  ..., -0.1151, -0.7360,  0.1616])
pissed
Saved the embedding for pissed.
['pit', '##iable'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2229, -1.1339,  0.0533,  ..., -0.8407, -0.8072, -0.6487])
pitiable
Saved the embedding for pitiable.
['pit', '##

['powerful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2738,  0.1499,  0.3632,  ..., -0.2916, -0.2934, -0.0113])
powerful
Saved the embedding for powerful.
['powerless'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1958, -0.0694,  0.2071,  ..., -0.8406, -1.2324, -0.8519])
powerless
Saved the embedding for powerless.
['prank', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3485, -0.4001, -0.5206,  ..., -0.6240, -1.0012,  0.4618])
pranking
Saved the embedding for pranking.
['pre', '##car', '##ious'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.4103,  0.2443, -0.2399,  ..., -0.5389, -0.7691,  0.3849])
precarious
Saved the embedding for precarious.
['predatory'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3917,  0.2845, -0.1428,  ...,  0.9762,  0.3138, -0.0302])
predatory
Saved the 

['que', '##as', '##y'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.3352,  0.7063,  0.4106,  ..., -0.3011, -1.2740,  0.4996])
queasy
Saved the embedding for queasy.
['que', '##nched'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3224, -0.1415, -0.2204,  ..., -0.0678, -0.9388,  0.6537])
quenched
Saved the embedding for quenched.
['questionable'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3475,  0.3021, -0.8337,  ..., -0.2981, -0.7257,  0.0645])
questionable
Saved the embedding for questionable.
['questioning'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2904, -0.2818, -0.8300,  ..., -0.8781,  0.1882, -0.8806])
questioning
Saved the embedding for questioning.
['questioning', '##ly'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2076,  0.1097, -0.4106,  ..., -0.1952, -0.1543, -0.3169])
ques

['rejecting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1185, -0.0544,  0.4597,  ..., -1.1933, -0.6023, -0.3045])
rejecting
Saved the embedding for rejecting.
['rejection'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4581,  0.2062,  0.7343,  ..., -0.4371, -1.4314, -0.7342])
rejection
Saved the embedding for rejection.
['re', '##jo', '##icing'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.3760, -0.1161, -0.1103,  ..., -0.7016,  0.0017,  0.7511])
rejoicing
Saved the embedding for rejoicing.
['relaxation'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0997,  0.6427, -0.2189,  ...,  0.7120, -0.2075,  0.3611])
relaxation
Saved the embedding for relaxation.
['relaxed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2606, -0.0365, -0.8659,  ..., -0.0367,  0.0330,  0.6860])
relaxed
Saved the embe

['restrained'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2817,  0.0823, -1.0393,  ...,  0.5340, -0.4884, -0.2083])
restrained
Saved the embedding for restrained.
['restraint'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0465,  0.0752, -0.5417,  ..., -0.2845, -0.1667,  0.6699])
restraint
Saved the embedding for restraint.
['re', '##tal', '##iating'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2190, -0.1833,  0.1695,  ..., -1.1697, -0.4748,  0.5674])
retaliating
Saved the embedding for retaliating.
['re', '##tal', '##ia', '##tory'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.3747, -0.7415, -0.4554,  ..., -0.5400, -0.2639,  0.7654])
retaliatory
Saved the embedding for retaliatory.
['re', '##thi', '##nk', '##ing'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.8047, -0.5670, -0.5228,  ...,

Saved the embedding for sardonic.
['sas', '##sy'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0438,  0.1940, -0.1508,  ..., -0.4937, -0.2421,  0.0228])
sassy
Saved the embedding for sassy.
['sat', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0456, -0.4159, -0.0143,  ..., -1.1127, -0.2302, -0.1753])
sated
Saved the embedding for sated.
['sat', '##iated'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1335, -0.1739,  0.1618,  ..., -1.2501,  0.3649, -0.3027])
satiated
Saved the embedding for satiated.
['satirical'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4114, -0.5536, -0.0288,  ...,  0.1422,  1.0783, -1.1552])
satirical
Saved the embedding for satirical.
['satisfaction'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8650,  0.5797,  0.9009,  ..., -0.2483,  0.0111, -0.7514])
satisfa

tensor([-0.2806,  0.2318,  0.2433,  ..., -0.1999, -0.8650,  0.3792])
serious
Saved the embedding for serious.
['seriousness'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1871,  0.3898, -0.0788,  ..., -0.3346, -0.4517,  0.0957])
seriousness
Saved the embedding for seriousness.
['ser', '##vil', '##e'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.3149,  0.4809,  0.2202,  ...,  0.0530,  0.4653, -0.3795])
servile
Saved the embedding for servile.
['set'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3708,  0.7113,  0.2428,  ..., -0.4708, -0.0215, -0.8212])
set
Saved the embedding for set.
['severe'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2007, -0.4291,  0.5088,  ..., -0.1023, -0.3207, -0.7126])
severe
Saved the embedding for severe.
['sha', '##bby'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor

['sincere'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1200,  0.7180, -0.0134,  ...,  0.0899, -0.0935,  0.6546])
sincere
Saved the embedding for sincere.
['sin', '##ful'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 1.2329,  0.3198, -0.3996,  ..., -0.4892,  0.2043,  0.0141])
sinful
Saved the embedding for sinful.
['singing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1661, -0.8219, -0.5743,  ...,  0.2603,  0.7173, -0.1210])
singing
Saved the embedding for singing.
['sinister'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 1.0293,  0.5042,  0.3203,  ..., -0.3881, -1.4783, -1.4583])
sinister
Saved the embedding for sinister.
['sinister', '##ly'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.6327,  0.2551,  0.0035,  ..., -0.5263, -0.2029, -0.0593])
sinisterly
Saved the embedding for sinisterly.

Saved the embedding for sneer.
['s', '##neer', '##ing'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.4242, -0.1950,  0.0203,  ..., -0.8040, -0.4864,  0.0769])
sneering
Saved the embedding for sneering.
['s', '##nee', '##ze'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.4711,  0.2463,  0.0877,  ..., -0.6244, -0.6009,  0.3075])
sneeze
Saved the embedding for sneeze.
['s', '##nee', '##zing'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2309, -0.0862, -0.2068,  ..., -0.9098, -0.4103,  0.2620])
sneezing
Saved the embedding for sneezing.
['s', '##nick', '##er'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.6130, -0.1989, -0.2863,  ..., -0.6643, -0.1115,  0.5918])
snicker
Saved the embedding for snicker.
['sq', '##ue', '##ami', '##sh'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.0921,  0.6798, -0

['strict'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.6179,  0.5700,  0.4778,  ..., -0.1759, -0.6239, -0.4757])
strict
Saved the embedding for strict.
['strong'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1234,  0.5532,  0.5631,  ..., -0.2607, -1.3304, -0.5509])
strong
Saved the embedding for strong.
['struck'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3018,  0.2384, -0.0854,  ..., -0.6200,  0.2721,  0.1383])
struck
Saved the embedding for struck.
['stubborn'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0442,  0.3723, -0.2966,  ..., -0.3460, -0.0067,  0.5375])
stubborn
Saved the embedding for stubborn.
['stubborn', '##ness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1971,  0.3531, -0.5590,  ..., -0.9929, -1.1900,  1.5029])
stubbornness
Saved the embedding for stubbornness.
['stu

['suspicion'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2837,  0.7158, -0.0529,  ...,  0.1140, -0.2760,  0.1162])
suspicion
Saved the embedding for suspicion.
['suspicious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1826,  0.4406,  0.3361,  ..., -0.9814, -0.8233, -0.2662])
suspicious
Saved the embedding for suspicious.
['suspiciously'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1922,  0.6071, -0.4325,  ...,  0.0774, -0.2413,  0.1772])
suspiciously
Saved the embedding for suspiciously.
['suspicious', '##ness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1307,  0.4970,  0.0823,  ..., -0.6268, -0.9094, -0.2070])
suspiciousness
Saved the embedding for suspiciousness.
['sw', '##agger', '##ing'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-4.1232e-01,  7.5793e-01, -5.9758e-01,  ...,  8.07

['thankful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1628,  0.5492, -0.2886,  ..., -0.5089, -0.7057,  0.3853])
thankful
Saved the embedding for thankful.
['thinking'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3176,  0.2977,  0.1630,  ...,  0.5015, -0.9690, -0.0370])
thinking
Saved the embedding for thinking.
['thought'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3511,  0.0719,  0.4473,  ...,  0.8665, -0.9827, -0.0242])
thought
Saved the embedding for thought.
['thoughtful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2982,  0.1888,  0.0709,  ..., -0.1188, -0.6362, -0.0546])
thoughtful
Saved the embedding for thoughtful.
['thoughtful', '##ness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0373,  0.2240, -0.0583,  ..., -0.1586, -0.3395,  0.2474])
thoughtfulness
Saved the embeddin

['tricky'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0343, -0.0995,  0.6134,  ...,  0.3390, -0.1536,  0.1458])
tricky
Saved the embedding for tricky.
['triumphant'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2170,  0.5429, -0.1384,  ..., -1.1918,  0.2806, -0.2118])
triumphant
Saved the embedding for triumphant.
['troubled'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4330,  0.8130, -0.7814,  ..., -0.4786, -0.5199,  0.4505])
troubled
Saved the embedding for troubled.
['troubles', '##ome'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.7822,  0.5786,  0.0603,  ..., -0.5149, -0.3670,  0.4227])
troublesome
Saved the embedding for troublesome.
['tr', '##ou', '##bling'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0855,  0.2538,  0.0584,  ..., -0.2724, -0.3464,  0.7572])
troubling
Saved the 

['un', '##cu', '##rio', '##us'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.2441,  0.0896, -1.0311,  ..., -0.0097,  0.2784,  0.5465])
uncurious
Saved the embedding for uncurious.
['und', '##ec', '##ided'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.6635,  0.3374, -0.3854,  ...,  0.0876, -0.5049,  0.4243])
undecided
Saved the embedding for undecided.
['under', '##hand', '##ed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1627, -0.0654, -0.7017,  ...,  0.0025, -0.9553,  0.8798])
underhanded
Saved the embedding for underhanded.
['understanding'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2486,  0.7745,  0.7579,  ...,  0.4240, -0.6672, -0.1672])
understanding
Saved the embedding for understanding.
['und', '##es', '##ira', '##ble'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.3857,  0.3759

['un', '##res', '##olved'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.3734, -0.3464, -1.0613,  ...,  0.0439,  0.3188,  0.6544])
unresolved
Saved the embedding for unresolved.
['unrest', '##rained'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0159,  0.5127,  0.8307,  ..., -0.8984, -0.7770, -0.5736])
unrestrained
Saved the embedding for unrestrained.
['un', '##ruff', '##led'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-7.9039e-01,  1.5122e-04, -1.4045e+00,  ...,  1.8214e-01,
         2.3196e-01,  3.0026e-01])
unruffled
Saved the embedding for unruffled.
['un', '##sat', '##is', '##fied'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-9.7142e-04, -7.7382e-02, -1.1457e+00,  ..., -1.7301e-01,
        -2.4074e-01,  9.0319e-02])
unsatisfied
Saved the embedding for unsatisfied.
['un', '##sett', '##led'] has a token embedding of size torch.

['ve', '##xed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3974, -0.1700,  0.1356,  ...,  0.0364, -1.4226,  0.5406])
vexed
Saved the embedding for vexed.
['vicious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3645,  0.7932,  0.4546,  ..., -0.0928, -0.9104, -0.0656])
vicious
Saved the embedding for vicious.
['victorious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0088, -0.1459,  0.0980,  ..., -0.5282, -0.8872, -0.7480])
victorious
Saved the embedding for victorious.
['vi', '##gil', '##ant'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 4.0692e-02, -1.2690e-01,  2.3587e-01,  ..., -2.6046e-01,
        -3.5716e-01,  3.2761e-04])
vigilant
Saved the embedding for vigilant.
['vile'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.9707,  0.3933,  1.0464,  ..., -0.2730, -0.5877, -0.5175])
vile
Sav

['wicked'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5564,  0.8588,  0.3279,  ...,  0.6275,  0.3978,  0.0556])
wicked
Saved the embedding for wicked.
['wild'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0407,  0.2602, -0.0314,  ..., -0.6516, -0.6798,  0.1538])
wild
Saved the embedding for wild.
['will', '##ful'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.7357,  0.6843,  0.0975,  ...,  0.2560, -0.2128,  0.1917])
willful
Saved the embedding for willful.
['willing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0754,  0.1801,  0.8074,  ..., -0.5072, -0.7769, -0.0117])
willing
Saved the embedding for willing.
['wil', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0458,  0.3267, -0.3480,  ..., -0.5323, -0.5748,  0.6810])
wily
Saved the embedding for wily.
['wink'] has a token embeddin

['yu', '##ck'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5949,  0.2492,  0.6811,  ...,  0.0486, -0.6737,  0.6232])
yuck
Saved the embedding for yuck.
['za', '##ny'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.6550,  1.2369, -0.9386,  ..., -1.0238, -0.5476,  0.5598])
zany
Saved the embedding for zany.
['ze', '##alo', '##us'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.8600, -0.2303, -0.6630,  ..., -0.3600,  0.3167, -0.0689])
zealous
Saved the embedding for zealous.
['zen'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1668,  0.3055, -0.4071,  ..., -0.5739, -0.3290,  0.5896])
zen
Saved the embedding for zen.
['zone', '##d'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.4880,  0.6528,  0.2187,  ..., -0.4170, -0.9627, -0.3530])
zoned
Saved the embedding for zoned.
