In [3]:
import sys
import os
from timeit import default_timer as timer
os.getcwd()

'/home/jupyter/Notebooks/crystal/NLP/nlp_testing'

In [ ]:
# Adapted from the tutorial at https://mccormickml.com/2019/05/14/BERT-word-embeddings-tutorial/

In [4]:
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
#logging.basicConfig(level=logging.INFO)

import matplotlib.pyplot as plt
%matplotlib inline

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [5]:
# list(tokenizer.vocab.keys())[5000:5020]
list(tokenizer.vocab.keys())[17733]

'disgusted'

In [ ]:
# Define a new example sentence with multiple meanings of the word "disgusted"
text = "[CLS] She made a disgusted pout [SEP] Her disgusted expression was contagious [SEP]"

# Split the sentence into tokens.
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)

# Map the token strings to their vocabulary indeces.
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

# Display the words with their indeces.
for tup in zip(tokenized_text, indexed_tokens):
    print('{:<12} {:>6,}'.format(tup[0], tup[1]))

In [ ]:
# Recreate vocabulary words from their tokenized representations.
for t in tokenized_text:
    this_word = ''
    for token in t:
        this_word += token.strip('#')
#     print(this_word)

In [ ]:
# Mark each of the tokens as belonging to sentence "0" or "1".

segments_ids = [1] * len(tokenized_text[3])
# segments_ids = [0,0,0]
print (segments_ids)
print(indexed_tokens)
print(tokenized_text[3])

In [ ]:
# Convert inputs to PyTorch tensors
tokens_tensor = torch.tensor([indexed_tokens[3]])
segments_tensors = torch.tensor([segments_ids])

# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-uncased')

# Put the model in "evaluation" mode, meaning feed-forward operation.
model.eval()

In [ ]:
# Predict hidden states features for each layer
with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, segments_tensors)

In [ ]:
print ("Number of layers:", len(encoded_layers))
layer_i = 0

print ("Number of batches:", len(encoded_layers[layer_i]))
batch_i = 0

print ("Number of tokens:", len(encoded_layers[layer_i][batch_i]))
token_i = 1

print ("Number of hidden units:", len(encoded_layers[layer_i][batch_i][token_i]))

In [ ]:
# For our token, select its feature values from layer 5.
token_i = 1
layer_i = 5
vec = encoded_layers[layer_i][batch_i][token_i]
# print(vec)

# Plot the values as a histogram to show their distribution.
plt.figure(figsize=(10,10))
plt.hist(vec, bins=200)
plt.show()

In [ ]:
# `encoded_layers` is a Python list.
print('     Type of encoded_layers: ', type(encoded_layers))

# Each layer in the list is a torch tensor.
print('Tensor shape for each layer: ', encoded_layers[0].size())

In [ ]:
# Concatenate the tensors for all layers. We use `stack` here to
# create a new dimension in the tensor.
token_embeddings = torch.stack(encoded_layers, dim=0)

token_embeddings.size()

In [ ]:
# Remove dimension 1, the "batches".
token_embeddings = torch.squeeze(token_embeddings, dim=1)

token_embeddings.size()

In [ ]:
# Swap dimensions 0 and 1.
token_embeddings = token_embeddings.permute(1,0,2)

token_embeddings.size()

In [23]:
# Concatenate the last 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_last = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_last.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_last), len(token_vecs_cat_last[0])))
print(token_vecs_cat_last[0])

Shape is: 1 x 3072
tensor([-0.2373,  0.8259, -0.6190,  ..., -0.3836, -0.5039,  0.6153])


In [24]:
# Sum the last 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_last = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[-4:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_last.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_last), len(token_vecs_sum_last[0])))

Shape is: 1 x 768


In [ ]:
# Concatenate the first 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_first = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[0], token[1], token[2], token[3]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_first.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_first), len(token_vecs_cat_first[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the first 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_first = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[:4], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_first.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_first), len(token_vecs_sum_first[0])))

In [ ]:
# Concatenate the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_middle1 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[4], token[5], token[6], token[7]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_middle1.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_middle1), len(token_vecs_cat_middle1[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_middle1 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[4:8], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_middle1.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_middle1), len(token_vecs_sum_middle1[0])))

In [ ]:
# Concatenate the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_middle2 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[8], token[9], token[10], token[11]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_middle2.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_middle2), len(token_vecs_cat_middle2[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_middle2 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[8:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_middle2.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_middle2), len(token_vecs_sum_middle2[0])))

In [ ]:
# Concatenate all hidden layers to create word embeddings.
token_vecs_cat_all = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[0], token[1], token[2], token[3], token[4], token[5], token[6], token[7], token[8], token[9], token[10], token[11]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_all.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_all), len(token_vecs_cat_all[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum all hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_all = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_all.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_all), len(token_vecs_sum_all[0])))

In [ ]:
# Make a single vector to represent the pair of sentences by averaging across tokens.
# `encoded_layers` has shape [12 x 1 x 22 x 768]
sentences_vec = []
# `token_vecs` is a tensor with shape [22 x 768]
token_vecs = encoded_layers[11][0]

# Calculate the average of all 22 token vectors.
sentence_embedding = torch.mean(token_vecs, dim=0)
for s in sentence_embedding:
    sentences_vec.append(s)
print ("Our final sentence embedding vector of shape:", sentence_embedding.size())
print(sentence_embedding[767])
print(sentence_embedding[-1])
print(f'Shape of sentences vector is: {len(sentences_vec)}')
print(sentences_vec[-1])

In [ ]:
from scipy.spatial.distance import cosine
# Test the similarity of a word with itself.
# For words trained contextually, self-synonymy is less than 1.
similarity = 1 - cosine(token_vecs_cat[0], token_vecs_cat[0])
print(f'Similarity of {tokenized_text[8]} and {tokenized_text[8]} in token_vecs_cat is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum[4], token_vecs_sum[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_first[4], token_vecs_cat_first[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_first is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_first[4], token_vecs_sum_first[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_first is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_middle1[4], token_vecs_cat_middle1[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_middle1 is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_middle1[4], token_vecs_sum_middle1[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_middle1 is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_middle2[4], token_vecs_cat_middle2[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_middle2 is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_middle2[4], token_vecs_sum_middle2[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_middle2 is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_all[4], token_vecs_cat_all[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_all is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_all[4], token_vecs_sum_all[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_all is: {similarity}')

In [7]:
######################################################################################
############## BEGIN TESTING STATIC CONTEXTUAL EMBEDDING CREATION ####################
######################################################################################

In [8]:
def make_vocab(vocab_file):
    # start = timer()
    vocab = []
    # vocab_file = '/home/jupyter/Notebooks/crystal/NLP/MiFace/Python/vocab_files/vocab_checked.txt'
    with open(vocab_file, 'r') as v:
        vocab = v.read().splitlines()
    # end = timer()
    # run_time = end - start
#     print(f'There are {len(vocab)} words in the vocabulary.\n')
#     print(f'It took {run_time} seconds to read the vocabulary file into memory.')
#     print(f'Test word is {vocab[2]}.')
    return vocab

In [9]:
def tokenize_text(vocab):
    tokenized_text = []
    indexed_tokens = []
    for word in vocab:
        # Add the special tokens.
    #     marked_text = "[CLS] " + word + " [SEP]"
        marked_text = word

        # Split the sentence into tokens.
        # tokenized_text = tokenizer.tokenize(marked_text)
        tokenized_text.append(tokenizer.tokenize(marked_text))
#         print(f'Added {tokenized_text[-1]} to the tokenized_text array.')


        # Map the token strings to their vocabulary indeces.
        indexed_tokens.append(tokenizer.convert_tokens_to_ids(tokenized_text[-1]))

        # Display the words with their indeces.
    #     print(f'The word {tokenized_text[-1][1]} is at index {indexed_tokens[-1]}.')
#         for tup in zip(tokenized_text[-1], indexed_tokens[-1]):
#             print('{:<12} {:>6,}'.format(tup[0], tup[1]))
    return tokenized_text, indexed_tokens

In [10]:
def generate_segments_IDs(tokenized_text):
    # Create segment IDs for sentence 1 (there can be a sentence 0 to compare to
    # sentence 1, but we're not doing that).
    # Check that indices and token indices look correct.
    segments_IDs = []
    for i in range(len(tokenized_text)):
        segments_IDs.append([1] * len(tokenized_text[i]))
#     for i in range(len(segments_IDs)):
#         print (segments_IDs[i])
#         print(tokenized_text[i])
    return segments_IDs

In [11]:
def generate_embeddings(indexed_tokens, segments_IDs):
    # Convert inputs to PyTorch tensors
    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_IDs])

    # Load pre-trained model (weights)
    model = BertModel.from_pretrained('bert-base-uncased')

    # Put the model in "evaluation" mode, meaning feed-forward operation.
    model.eval()

    # Predict hidden states features for each layer
    with torch.no_grad():
        encoded_layers, _ = model(tokens_tensor, segments_tensors)
#         print('Type of encoded_layers: ', type(encoded_layers))
        # Each layer in the list is a torch tensor.
#         print('Tensor shape for each layer: ', encoded_layers[0].size())

    # Concatenate the tensors for all layers. We use `stack` here to
    # create a new dimension in the tensor.
    token_embeddings = torch.stack(encoded_layers, dim=0)
#     print(token_embeddings.size())

    # Remove dimension 1, the "batches".
    token_embeddings = torch.squeeze(token_embeddings, dim=1)
#     print(token_embeddings.size())

    # Swap dimensions 0 and 1.
    token_embeddings = token_embeddings.permute(1,0,2)
#     print(token_embeddings.size())
    
    return token_embeddings

In [12]:
def cat_last_four(token_embeddings): 
    # Concatenate the last 4 hidden layers to create contextual embeddings.
    # Stores the token vectors, with shape [22 x 3,072]
    token_vecs_cat_last = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_last.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_last), len(token_vecs_cat_last[0])))
    print(token_vecs_cat_last[0])
    
    return token_vecs_cat_last

In [22]:
def cat_first_four(token_embeddings):
    token_vecs_cat_first = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last 
        # four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[0], token[1], token[2], token[3]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_first.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_first), len(token_vecs_cat_first[0])))
    print(token_vecs_cat_first[0])
    
    return token_vecs_cat_first

In [14]:
def get_mean_embedding(token_embeddings):
    mean_embedding = sum(token_embeddings) / len(token_embeddings)
    print(mean_embedding)
    
    return mean_embedding

In [15]:
def reconstruct_tokens(tokenized_text):
    vocab_word = ''
    for i in tokenized_text:
        vocab_word += i.strip('#')
    print(vocab_word)

    return vocab_word

In [16]:
def write_embedding(embeddings_file, vocab_word, contextual_embedding):
    try:
        with open(embeddings_file, 'a') as f:
            f.write(vocab_word)
            for value in contextual_embedding[0]:
                f.write(' ' + str(value.item()))
            f.write('\n')
        print(f'Saved the embedding for {vocab_word}.')
    except:
        print('Oh no! Unable to write to the embeddings file.')

In [ ]:
# if __name__ == "__main__":
# Set up input and output paths.
vocab_file = '/home/jupyter/Notebooks/crystal/NLP/MiFace/Python/vocab_files/vocab_checked.txt'
layer_combining_function = cat_first_four
embeddings_file = os.path.join('/home/jupyter/Notebooks/crystal/NLP/nlp_testing/embeddings_context_vocab', layer_combining_function.__name__ + '.txt')
if os.path.exists(embeddings_file):
    os.remove(embeddings_file)

# Create a list of vocabulary words we want embeddings for.
vocab = make_vocab(vocab_file)

# Tokenize the vocabulary and look up the BERT token indices.
tokenized_text, indexed_tokens = tokenize_text(vocab)

# Generate segment IDs for each token.
segments_IDs = generate_segments_IDs(tokenized_text)

# Generate and write out the contextual embeddings for the vocabulary words.
# Embeddings are saved in a standard format that can be used for calcualting
# the cosine distances between word vectors.
for i in range(len(tokenized_text)):
    # Convert indexed tokens and segments to tensors.
    # Create a BERT model for the tokens.
    # Get the encoded model layers and reshape them.
    token_embeddings = generate_embeddings(indexed_tokens[i], segments_IDs[i])
    print(f'{tokenized_text[i]} has a token embedding of size {token_embeddings.size()}')

    # Extract the contextual embedding for a token.
    contextual_embedding = layer_combining_function(token_embeddings)

    # Write the embedding to a text file, with the vocabulary word prepended.
    vocab_word = reconstruct_tokens(tokenized_text[i])
    # Make sure we've got the correct vocabulary word.
    assert vocab[i] == vocab_word
    write_embedding(embeddings_file, vocab[i], contextual_embedding)

['aback'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5053,  0.4971,  0.0317,  ..., -0.9494,  0.5799,  0.7537])
aback
Saved the embedding for aback.
['aba', '##shed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1385,  0.1992, -0.6109,  ..., -0.1529,  0.0258, -0.1901])
abashed
Saved the embedding for abashed.
['ab', '##hor'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0943,  0.3695, -1.2897,  ...,  0.1303,  0.2182,  0.5159])
abhor
Saved the embedding for abhor.
['ab', '##hor', '##red'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0665,  0.2880, -1.2760,  ...,  0.0154,  0.2874,  0.4358])
abhorred
Saved the embedding for abhorred.
['ab', '##hor', '##rence'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0444,  0.3661, -1.2157,  ..., -0.0860,  0.2170,  0.4015])
abhorrence
Saved the embedding 

['aggravated'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1777,  0.4265, -0.1913,  ..., -0.1204, -0.2994,  0.2673])
aggravated
Saved the embedding for aggravated.
['ag', '##gra', '##vation'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0667,  1.0663, -0.3278,  ..., -0.1178,  0.6243,  0.8914])
aggravation
Saved the embedding for aggravation.
['aggression'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1853,  1.0595, -0.3109,  ..., -0.1024, -0.0157,  0.5554])
aggression
Saved the embedding for aggression.
['aggressive'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0088,  0.5032, -0.5507,  ..., -0.0484,  0.1403,  0.2706])
aggressive
Saved the embedding for aggressive.
['ag', '##gr', '##ie', '##ve'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.1614,  0.7959, -0.3026,  ..., -0.2129,  0.8440,  

['angry'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1087,  0.5733, -0.3362,  ..., -0.0491,  0.3709,  0.4512])
angry
Saved the embedding for angry.
['ang', '##st'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.3287,  0.1654, -0.1497,  ..., -0.2954,  0.2572,  0.5989])
angst
Saved the embedding for angst.
['anguish'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3491,  0.3474, -0.4197,  ...,  0.1957,  0.3298,  0.0772])
anguish
Saved the embedding for anguish.
['anguish', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2998,  0.3180, -0.4168,  ...,  0.1504,  0.3565,  0.3088])
anguished
Saved the embedding for anguished.
['animated'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1402,  0.2226, -0.3230,  ...,  0.6311,  0.7730,  0.6633])
animated
Saved the embedding for animated.
['an', '##i

['artificial'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3631,  0.4375, -0.0695,  ..., -0.8754, -0.4007,  0.5359])
artificial
Saved the embedding for artificial.
['ashamed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0583, -0.0833, -0.4251,  ..., -0.1705, -0.1941,  0.0921])
ashamed
Saved the embedding for ashamed.
['aspiring'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3538, -0.2145, -0.2146,  ..., -0.4136,  0.1431, -0.1170])
aspiring
Saved the embedding for aspiring.
['assert', '##ive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.6213,  0.4932, -0.4482,  ..., -0.3063, -0.0021,  0.6945])
assertive
Saved the embedding for assertive.
['assert', '##ively'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.6273,  0.3859, -0.3971,  ...,  0.1550, -0.0304,  0.5407])
assertively
Saved the embed

['bear', '##ish'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3202,  0.2045, -0.1138,  ..., -0.0706,  0.2217,  0.2988])
bearish
Saved the embedding for bearish.
['beat'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([0.4377, 0.1360, 0.2417,  ..., 0.8847, 0.1448, 0.0081])
beat
Saved the embedding for beat.
['beaten'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0072, -0.1867,  0.2120,  ...,  0.4141,  0.0417,  0.3091])
beaten
Saved the embedding for beaten.
['bed', '##ev', '##iled'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.6281,  0.1020,  0.0128,  ...,  0.5353, -0.1057, -0.0246])
bedeviled
Saved the embedding for bedeviled.
['be', '##fu', '##ddled'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.3044,  0.2001, -0.5320,  ...,  0.3145,  0.0343,  0.3894])
befuddled
Saved the embedding for befuddl

['blazed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2652, -0.3125, -0.0259,  ..., -0.1631,  0.0746,  0.4862])
blazed
Saved the embedding for blazed.
['bleak'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4755,  0.3233,  0.0442,  ..., -0.2899, -0.1171,  0.2193])
bleak
Saved the embedding for bleak.
['b', '##lea', '##ry'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.3839,  0.1876, -0.3379,  ...,  0.1590, -0.1931,  0.3375])
bleary
Saved the embedding for bleary.
['blessed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5355,  0.6504,  0.1743,  ..., -0.8914,  0.5753,  0.7794])
blessed
Saved the embedding for blessed.
['blew'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8021, -0.0257, -0.1239,  ..., -0.0482, -0.1299, -0.3386])
blew
Saved the embedding for blew.
['blinded'] has a token embed

['bulging'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0669,  0.1745, -0.3350,  ..., -0.1227, -0.0248,  0.1602])
bulging
Saved the embedding for bulging.
['bully'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4920,  0.3804, -0.4935,  ..., -0.3690, -0.2565,  0.0201])
bully
Saved the embedding for bully.
['bullying'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3058,  0.0328, -0.0401,  ..., -0.2273, -0.7757,  0.6153])
bullying
Saved the embedding for bullying.
['bum', '##med'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1330, -0.1384, -0.2175,  ...,  0.0494, -0.6765,  0.0928])
bummed
Saved the embedding for bummed.
['bu', '##oya', '##nt'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1191,  0.1376, -0.1909,  ..., -0.5604,  0.0903,  0.2858])
buoyant
Saved the embedding for buoyant.
['burden

['challenge'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0204, -0.2608,  0.3331,  ...,  0.1052,  0.7287,  0.6897])
challenge
Saved the embedding for challenge.
['challenged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2364,  0.5663,  0.0222,  ..., -0.3951,  0.3021,  0.3892])
challenged
Saved the embedding for challenged.
['challenging'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0647,  0.7027, -0.2624,  ..., -0.2490, -0.0319,  0.4787])
challenging
Saved the embedding for challenging.
['chaotic'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3906,  0.3860, -0.1002,  ...,  0.1654, -0.1062,  0.3752])
chaotic
Saved the embedding for chaotic.
['charged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3493,  0.4843, -0.0217,  ...,  0.1029,  0.0098,  0.3579])
charged
Saved the embedding for ch

['cl', '##oy'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3940,  0.0672,  0.1482,  ..., -0.8301, -0.3035,  0.1026])
cloy
Saved the embedding for cloy.
['clue', '##less'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3537,  0.3516, -0.0855,  ...,  0.5450,  0.2079, -0.0888])
clueless
Saved the embedding for clueless.
['clutched'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0729,  0.3757,  0.1242,  ...,  0.0318,  0.1232, -0.1958])
clutched
Saved the embedding for clutched.
['cl', '##uttered'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4329, -0.2650,  0.0659,  ..., -0.8252, -0.6034,  0.2607])
cluttered
Saved the embedding for cluttered.
['cock', '##eye', '##d'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.9640,  0.4649,  0.4256,  ...,  0.1946,  0.3907, -0.1313])
cockeyed
Saved the embeddin

['concentrating'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2736,  0.7871, -0.5414,  ..., -0.1986, -0.5291,  0.2288])
concentrating
Saved the embedding for concentrating.
['concentration'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5585,  0.8898,  0.1307,  ...,  0.0498, -0.3890,  0.9829])
concentration
Saved the embedding for concentration.
['concern'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0735,  1.1418, -0.2573,  ..., -0.2009, -0.3959,  0.6723])
concern
Saved the embedding for concern.
['concerned'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6350,  1.3573, -0.5785,  ..., -0.0888, -0.2742,  0.6826])
concerned
Saved the embedding for concerned.
['con', '##ci', '##lia', '##tory'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.2814, -0.3759,  0.0206,  ..., -0.0013,  0.1002,  0.486

['contempt', '##uous'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4750,  0.2948, -0.2885,  ..., -0.4888,  0.3629,  0.4760])
contemptuous
Saved the embedding for contemptuous.
['content'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2564, -0.0685,  0.6076,  ..., -0.1711, -0.0511,  0.1385])
content
Saved the embedding for content.
['content', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1705, -0.1354,  0.5390,  ..., -0.2559,  0.0701,  0.1324])
contented
Saved the embedding for contented.
['contentious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2854,  0.1342,  0.0460,  ..., -0.2448, -0.2145,  0.3199])
contentious
Saved the embedding for contentious.
['content', '##ly'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1278,  0.0149,  0.6229,  ..., -0.0146, -0.1392,  0.1582])
contentl

['cu', '##rio', '##s'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0337, -0.5441, -0.4350,  ...,  0.1675,  0.3036,  0.5885])
curios
Saved the embedding for curios.
['curiosity'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0589,  0.4582,  0.8356,  ..., -0.2349,  0.2514,  0.9339])
curiosity
Saved the embedding for curiosity.
['curious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1513,  0.2871,  0.3003,  ...,  0.1859,  0.5808,  0.7026])
curious
Saved the embedding for curious.
['cutting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4853, -0.6611, -0.5175,  ...,  0.2412, -0.1532,  0.1422])
cutting
Saved the embedding for cutting.
['cy', '##nic'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4712,  0.5292,  0.0404,  ..., -0.2838, -0.0478,  0.5956])
cynic
Saved the embedding for cynic.
['cyn

['deliberate'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8562,  0.4208, -0.1099,  ..., -0.7405,  0.3538,  0.1408])
deliberate
Saved the embedding for deliberate.
['del', '##ibe', '##rating'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.1727, -0.0362, -0.1247,  ..., -0.1217,  0.6730, -0.0385])
deliberating
Saved the embedding for deliberating.
['delight'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0059,  0.0936,  0.1161,  ...,  0.1278,  0.1939, -0.0528])
delight
Saved the embedding for delight.
['delighted'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3622,  0.0283,  0.1005,  ..., -0.1933,  0.2001,  0.2265])
delighted
Saved the embedding for delighted.
['delightful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2171,  0.3035,  0.2798,  ..., -0.4540, -0.2300,  0.2704])
delightful
Saved

['detached'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2938, -0.3780, -0.2961,  ..., -0.5731, -0.1811,  0.8537])
detached
Saved the embedding for detached.
['determination'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4880,  0.5368, -0.6584,  ..., -0.5456,  0.2716,  0.6208])
determination
Saved the embedding for determination.
['determined'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1321,  0.5865, -0.4246,  ..., -0.0625,  0.3426,  0.6296])
determined
Saved the embedding for determined.
['determining'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3774,  1.0257, -0.5345,  ..., -0.1861, -0.2725,  0.7019])
determining
Saved the embedding for determining.
['deter', '##red'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4926,  0.4516, -0.5377,  ..., -0.4418, -0.5398,  0.5830])
deterred
Sav

['discontent', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.3166,  0.1076, -0.2163,  ...,  0.2748, -0.2628,  0.1450])
discontented
Saved the embedding for discontented.
['discount', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.4470, -0.3483, -0.0346,  ...,  0.3565,  0.3051,  0.3686])
discounted
Saved the embedding for discounted.
['discouraged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6820,  0.0201, -0.8367,  ..., -1.0486, -0.3584,  0.5964])
discouraged
Saved the embedding for discouraged.
['discovery'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3987, -0.3133, -0.0142,  ..., -0.1192,  0.4577,  0.0703])
discovery
Saved the embedding for discovery.
['disc', '##rim', '##inating'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2959, -0.1703, -0.1225,  ...,  0.1623,  0.4603

['di', '##spar', '##aging'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.1468, -0.3479, -0.1235,  ..., -0.1063,  0.2488,  0.6816])
disparaging
Saved the embedding for disparaging.
['di', '##sp', '##ass', '##ion', '##ate'] has a token embedding of size torch.Size([5, 12, 768])
Shape is: 5 x 3072
tensor([ 0.2805, -0.3286, -0.0962,  ..., -0.0583,  0.5164,  0.7174])
dispassionate
Saved the embedding for dispassionate.
['di', '##sp', '##iri', '##ted'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.3227, -0.4280, -0.0614,  ..., -0.1769,  0.4249,  0.4843])
dispirited
Saved the embedding for dispirited.
['di', '##sp', '##iri', '##ted', '##ness'] has a token embedding of size torch.Size([5, 12, 768])
Shape is: 5 x 3072
tensor([ 0.3150, -0.4154, -0.0340,  ..., -0.2423,  0.3704,  0.4814])
dispiritedness
Saved the embedding for dispiritedness.
['di', '##sp', '##lea', '##sed'] has a token embedding of size torch.Size([4, 

['doomed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4431, -0.0569, -0.1926,  ...,  0.2137, -0.0587,  0.1960])
doomed
Saved the embedding for doomed.
['do', '##pe', '##y'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.1215, -0.2783, -0.4336,  ...,  0.3338, -0.0433,  0.2783])
dopey
Saved the embedding for dopey.
['dot', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3917, -0.0688, -0.4580,  ...,  0.1827,  0.3892,  0.9523])
doting
Saved the embedding for doting.
['doubt'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.6401, -0.2576, -0.3894,  ...,  0.0657, -0.0948,  0.2754])
doubt
Saved the embedding for doubt.
['doubt', '##er'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.6319, -0.2027, -0.3952,  ...,  0.1878,  0.0250,  0.3404])
doubter
Saved the embedding for doubter.
['doubtful'] h

Saved the embedding for duplicitous.
['d', '##ys', '##ph', '##oric'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.0143,  0.4767, -0.0647,  ..., -0.1957, -0.0123,  0.3296])
dysphoric
Saved the embedding for dysphoric.
['eager'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1798, -0.0618,  0.1392,  ...,  0.0858,  0.4320,  0.0667])
eager
Saved the embedding for eager.
['eager', '##ness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2770, -0.0415,  0.1982,  ...,  0.2867,  0.4079,  0.3165])
eagerness
Saved the embedding for eagerness.
['earnest'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1098,  0.6345,  0.1075,  ..., -0.5859,  0.7765,  0.0462])
earnest
Saved the embedding for earnest.
['easy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6286, -0.1051, -0.5452,  ..., -0.0014, -0.0387,  0.7186

Saved the embedding for energized.
['engaged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2886,  0.9410, -0.2154,  ..., -0.9590, -0.4393, -0.1185])
engaged
Saved the embedding for engaged.
['eng', '##ross', '##ed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1748,  0.4167, -0.3022,  ...,  0.1660,  0.4460,  1.0606])
engrossed
Saved the embedding for engrossed.
['eng', '##ross', '##ment'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2296,  0.3986, -0.3508,  ...,  0.1479,  0.5014,  1.0224])
engrossment
Saved the embedding for engrossment.
['enigma', '##tic'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([0.9478, 0.8079, 0.3330,  ..., 0.3836, 0.2270, 0.9118])
enigmatic
Saved the embedding for enigmatic.
['enjoy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1463, -0.2680,  0.9499,  ..., -0.0420,

['ex', '##cl', '##ama', '##tory'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.4919, -0.6570,  0.3935,  ..., -0.8711,  0.2260,  0.3995])
exclamatory
Saved the embedding for exclamatory.
['exhausted'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0528,  0.1054, -0.4832,  ..., -0.2470, -0.0791, -0.1748])
exhausted
Saved the embedding for exhausted.
['exhaustion'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1942, -0.0943, -0.2555,  ..., -0.1647, -0.1238,  0.1015])
exhaustion
Saved the embedding for exhaustion.
['exhaust', '##ive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2761,  0.1334, -0.6596,  ..., -0.2392, -0.2967, -0.0298])
exhaustive
Saved the embedding for exhaustive.
['ex', '##hila', '##rated'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.4906, -0.5937,  0.3160,  ..., -0.9157,  0.2

['fear'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2452,  0.6029, -0.0857,  ...,  0.2375, -0.1638,  0.3226])
fear
Saved the embedding for fear.
['feared'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2403,  0.4179, -0.4202,  ..., -0.0637,  0.0877, -0.0051])
feared
Saved the embedding for feared.
['fearful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1797,  0.3532, -0.3933,  ..., -0.0917,  0.0640,  0.4447])
fearful
Saved the embedding for fearful.
['fearing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1652,  0.4260, -0.3647,  ...,  0.1443,  0.0216,  0.2843])
fearing
Saved the embedding for fearing.
['fearless'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0620, -0.0822, -0.1728,  ...,  0.0148,  0.3252,  0.0297])
fearless
Saved the embedding for fearless.
['fears', '##ome'] has a toke

['foil', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.5514,  0.2605, -0.7877,  ...,  0.3268,  0.2366,  0.4914])
foiled
Saved the embedding for foiled.
['foolish'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4449,  0.4786, -0.2532,  ..., -0.2759,  0.0371,  0.2724])
foolish
Saved the embedding for foolish.
['for', '##be', '##aring'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0688,  0.1661, -0.3011,  ...,  0.0129,  0.1739,  0.1552])
forbearing
Saved the embedding for forbearing.
['forbid', '##ding'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3827, -0.4935, -0.6576,  ..., -0.0187,  0.2286,  0.4612])
forbidding
Saved the embedding for forbidding.
['forced'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0917,  0.1033, -0.1248,  ..., -0.1484,  0.0104, -0.1050])
forced
Saved the embedd

Saved the embedding for furiously.
['furious', '##ness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3378,  0.3463, -0.4172,  ..., -0.0222,  0.2270,  0.3938])
furiousness
Saved the embedding for furiousness.
['furrowed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4799,  0.3043,  0.1316,  ..., -0.5064,  0.1892,  0.8059])
furrowed
Saved the embedding for furrowed.
['fur', '##tive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 1.1522e+00, -3.8490e-02,  7.4933e-02,  ...,  6.0025e-01,
         2.8969e-02, -5.6099e-05])
furtive
Saved the embedding for furtive.
['fury'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.6815,  0.7525, -0.1880,  ...,  0.0153,  0.0677,  1.0174])
fury
Saved the embedding for fury.
['fuss', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0290,  0.5835, -0.1452,  ..., 

Saved the embedding for gossipy.
['grand', '##ios', '##e'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0383,  0.2587,  0.0788,  ...,  0.1125,  0.7770, -0.1776])
grandiose
Saved the embedding for grandiose.
['grateful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1822, -0.0873, -0.1045,  ..., -0.1729,  0.0530,  0.2081])
grateful
Saved the embedding for grateful.
['gr', '##ati', '##fied'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.1211,  0.6361, -0.0200,  ...,  0.0045,  0.6254,  0.2492])
gratified
Saved the embedding for gratified.
['grave'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8479,  0.9344,  0.8660,  ...,  0.9750, -0.0179,  0.2429])
grave
Saved the embedding for grave.
['great'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.7490,  0.4810, -0.2799,  ..., -0.5230, -0.2337,  0.3300

tensor([ 0.3381,  0.2329, -0.1851,  ...,  0.5196, -0.1550,  0.5209])
harried
Saved the embedding for harried.
['harsh'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2747,  0.2842, -0.4022,  ..., -0.0969, -0.0698,  0.4317])
harsh
Saved the embedding for harsh.
['hate'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.9027, -0.2999,  0.3711,  ..., -0.0368, -0.2031,  0.4605])
hate
Saved the embedding for hate.
['hate', '##ful'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.7968, -0.2704,  0.3350,  ...,  0.0441, -0.0605,  0.4968])
hateful
Saved the embedding for hateful.
['hating'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8412, -0.0999,  0.0242,  ..., -0.1772, -0.4065,  0.3038])
hating
Saved the embedding for hating.
['hatred'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.9902,  0.5283,  0.4363

['hostility'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0895,  0.6521,  0.3080,  ..., -0.1003, -0.2476,  0.8552])
hostility
Saved the embedding for hostility.
['hot'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2074,  0.7575,  0.2572,  ...,  0.2020, -0.0610, -0.3649])
hot
Saved the embedding for hot.
['hot', '##shot'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2155,  0.5019,  0.1216,  ..., -0.0714, -0.0617, -0.0248])
hotshot
Saved the embedding for hotshot.
['huff', '##iness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0021,  0.1788,  0.1279,  ..., -0.3272,  0.2685,  0.5619])
huffiness
Saved the embedding for huffiness.
['huff', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1684,  0.2632,  0.0286,  ..., -0.2182,  0.1577,  0.4711])
huffy
Saved the embedding for huffy.
['humble

['imp', '##eri', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0290, -0.7077, -0.2537,  ..., -0.5293,  0.9145,  0.2232])
imperious
Saved the embedding for imperious.
['imp', '##erson', '##al'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.0750, -0.5264,  0.0288,  ..., -0.0569,  0.5741,  0.4571])
impersonal
Saved the embedding for impersonal.
['imp', '##ert', '##inen', '##t'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.1078, -0.4653,  0.0110,  ..., -0.1923,  0.9028,  0.4740])
impertinent
Saved the embedding for impertinent.
['imp', '##ish'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0254, -0.5142, -0.2901,  ...,  0.2822,  0.8012,  0.2197])
impish
Saved the embedding for impish.
['implicated'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2077,  0.5269, -0.2716,  ..., -0.1222, -0.09

tensor([ 0.1348,  0.2185, -0.1920,  ..., -0.1003, -0.3064,  0.6496])
inferiority
Saved the embedding for inferiority.
['in', '##fl', '##ame', '##d'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.1032,  0.2138, -0.2047,  ..., -0.4607,  0.2318,  0.3050])
inflamed
Saved the embedding for inflamed.
['informal'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1791,  0.3097, -0.3757,  ..., -0.3587, -0.4306,  0.5497])
informal
Saved the embedding for informal.
['informing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.6437,  0.6986,  0.3009,  ..., -0.1465,  0.4077,  0.4383])
informing
Saved the embedding for informing.
['in', '##fur', '##iated'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1376,  0.1891, -0.0154,  ..., -0.4405, -0.0213,  0.4322])
infuriated
Saved the embedding for infuriated.
['inhibit', '##ed'] has a token embedding of si

['intentional'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1615,  0.4315, -0.4196,  ..., -0.6789, -0.4150,  0.4007])
intentional
Saved the embedding for intentional.
['interacting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2600,  0.8846, -0.1628,  ...,  0.1640, -0.5290,  0.6244])
interacting
Saved the embedding for interacting.
['interest'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3102,  0.6932,  0.0425,  ..., -0.5996,  0.1604,  0.2487])
interest
Saved the embedding for interest.
['interested'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4841,  0.8182,  0.3977,  ...,  0.1230,  0.3180,  0.4607])
interested
Saved the embedding for interested.
['inter', '##ject', '##ing'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2382, -0.2433, -0.3429,  ..., -0.5755,  0.3374,  0.9885])
interjec

['jaw', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.7195,  0.5620, -0.4159,  ..., -0.1774,  0.2825,  0.4160])
jawed
Saved the embedding for jawed.
['jealous'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.6075,  0.3273, -0.1386,  ..., -1.2928, -0.0568, -0.0300])
jealous
Saved the embedding for jealous.
['je', '##ering'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4695, -0.3845, -0.3876,  ...,  0.5425,  0.2888,  0.0381])
jeering
Saved the embedding for jeering.
['je', '##sti', '##ng'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.4082, -0.3387, -0.3067,  ...,  0.7558,  0.1073,  0.0127])
jesting
Saved the embedding for jesting.
['ji', '##lt', '##ed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.1360, -0.1692, -0.5378,  ..., -0.0190, -0.0608,  0.2691])
jilted
Saved the embedding for j

['laughter'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1382,  0.8906,  0.1930,  ...,  0.0436, -0.0291,  0.3775])
laughter
Saved the embedding for laughter.
['lazy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0948,  0.4938, -0.4840,  ...,  0.0551, -0.1624,  0.9168])
lazy
Saved the embedding for lazy.
['leaving'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3882, -0.4447, -0.0862,  ...,  0.3898,  0.3494, -0.0062])
leaving
Saved the embedding for leaving.
['le', '##cher', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2661, -0.0326, -0.0825,  ...,  0.8955,  0.5646,  0.3913])
lecherous
Saved the embedding for lecherous.
['le', '##cturing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.3441, -0.0849,  0.1715,  ...,  0.8347,  0.3704,  0.3738])
lecturing
Saved the embedding for lecturi

['lying'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0748,  0.3907, -0.0999,  ...,  0.6169, -0.2985, -0.0864])
lying
Saved the embedding for lying.
['mad'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0438,  0.4377,  0.1243,  ..., -0.0119,  0.0104,  0.5819])
mad
Saved the embedding for mad.
['madden', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1222, -0.1420, -0.3225,  ..., -0.4062,  0.5032,  0.5225])
maddened
Saved the embedding for maddened.
['madness'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.7415, -0.0390, -0.2906,  ..., -0.0780,  0.0876,  0.4792])
madness
Saved the embedding for madness.
['mal', '##con', '##ten', '##t'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.7811,  0.2633, -0.5221,  ..., -0.0103, -0.2486,  0.0994])
malcontent
Saved the embedding for malcontent.
['

Saved the embedding for musing.
['muster'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.9586,  0.1123, -0.2081,  ..., -0.4346,  0.2927, -0.0714])
muster
Saved the embedding for muster.
['mute'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3308, -0.5543, -0.6141,  ..., -0.4294, -0.1583,  0.0776])
mute
Saved the embedding for mute.
['muted'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2849,  0.3311, -0.4252,  ...,  0.1261, -0.3527,  0.3089])
muted
Saved the embedding for muted.
['muttering'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8662,  0.1653,  0.0413,  ..., -0.1038, -0.0553,  0.0615])
muttering
Saved the embedding for muttering.
['mysterious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1698, -0.0312,  0.1336,  ..., -0.3727,  0.2685,  0.3178])
mysterious
Saved the embedding for mys

Saved the embedding for nonplussed.
['non', '##sen', '##sic', '##al'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.1973, -0.3265,  0.3079,  ...,  0.1393,  0.1082,  1.0119])
nonsensical
Saved the embedding for nonsensical.
['normal'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3529,  0.4992, -0.4382,  ..., -0.5344, -0.5981, -0.1805])
normal
Saved the embedding for normal.
['nose', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0123,  0.3035, -0.3556,  ..., -0.1469, -0.5449,  0.3188])
nosey
Saved the embedding for nosey.
['nos', '##tal', '##gic'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([0.1617, 0.0359, 0.3540,  ..., 0.8199, 0.1464, 0.6509])
nostalgic
Saved the embedding for nostalgic.
['nos', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([0.0593, 0.1326, 0.2221,  ..., 0.8368, 0.3220

['out', '##land', '##ish'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2334, -0.2680, -0.0446,  ...,  0.3290, -0.0056,  0.5121])
outlandish
Saved the embedding for outlandish.
['outrage'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2590,  0.7965, -0.5729,  ...,  0.3096,  0.1675,  0.1394])
outrage
Saved the embedding for outrage.
['outraged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4489,  0.6013, -0.6594,  ...,  0.0011, -0.0030, -0.1122])
outraged
Saved the embedding for outraged.
['outspoken'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1734,  0.3273,  0.3024,  ..., -0.3535, -0.1921, -0.0766])
outspoken
Saved the embedding for outspoken.
['over', '##be', '##aring'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.4418, -0.1120, -0.0943,  ..., -0.1714, -0.2104,  0.5628])
overbearing
Sav

['persona', '##ble'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2759,  0.1128, -0.1462,  ..., -0.2898,  0.5211,  0.1132])
personable
Saved the embedding for personable.
['per', '##tur', '##bed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.3997,  0.1081, -0.3668,  ..., -0.3496,  0.4613,  0.3961])
perturbed
Saved the embedding for perturbed.
['per', '##verse'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4128,  0.0224, -0.3874,  ..., -0.1934,  0.5164,  0.1428])
perverse
Saved the embedding for perverse.
['pe', '##sky'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2723,  0.1761, -0.7887,  ...,  0.3089, -0.3488, -0.0271])
pesky
Saved the embedding for pesky.
['pe', '##ssi', '##mism'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2421, -0.0604, -0.5625,  ...,  0.0710,  0.3449, -0.1649])
pessi

['polite'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1785,  0.4174, -0.3249,  ..., -0.4270, -0.0143,  0.8588])
polite
Saved the embedding for polite.
['po', '##mp', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2711,  0.3297, -0.6411,  ..., -0.1427,  0.1291,  0.7437])
pompous
Saved the embedding for pompous.
['ponder'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5642,  0.5386,  0.4570,  ..., -0.2422,  0.3581,  0.4724])
ponder
Saved the embedding for ponder.
['ponder', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3983,  0.4869,  0.3603,  ..., -0.4694,  0.6233,  0.3477])
pondering
Saved the embedding for pondering.
['po', '##oping'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2244,  0.4079, -0.6606,  ..., -0.2461, -0.5050,  0.8045])
pooping
Saved the embedding for poopi

['punished'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2467,  0.2137, -0.4076,  ...,  0.0979,  0.4396,  0.0455])
punished
Saved the embedding for punished.
['punish', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1025, -0.0499, -0.3159,  ...,  0.3229,  0.3798,  0.4320])
punishing
Saved the embedding for punishing.
['pun', '##itive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1760, -0.0548, -0.3208,  ..., -0.2206, -0.3533, -0.0361])
punitive
Saved the embedding for punitive.
['punk'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3872,  0.6341, -0.6864,  ...,  0.1003, -0.5454,  0.0649])
punk
Saved the embedding for punk.
['puppy', '##ish'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2406, -0.2310,  0.3293,  ...,  0.2664,  0.3756,  0.9249])
puppyish
Saved the embedding for puppyi

['recalling'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([0.1709, 0.8338, 0.0508,  ..., 0.0672, 0.2810, 0.2729])
recalling
Saved the embedding for recalling.
['rec', '##eptive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0342, -0.0182,  0.1114,  ..., -0.3687,  0.0820,  0.3293])
receptive
Saved the embedding for receptive.
['reckless'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1823,  0.3304, -0.6604,  ..., -0.5077, -0.3635,  0.0955])
reckless
Saved the embedding for reckless.
['recoil'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5120,  1.0294,  0.0611,  ..., -0.0231, -0.3080, -0.0841])
recoil
Saved the embedding for recoil.
['recoil', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3490,  1.1179,  0.0558,  ..., -0.0735, -0.1288, -0.0122])
recoiling
Saved the embedding for recoili

['res', '##ili', '##ence'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.5423, -0.1000,  0.3036,  ...,  0.0665,  0.4009,  0.9513])
resilience
Saved the embedding for resilience.
['resistance'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0683,  0.5221, -0.3828,  ...,  0.5187, -0.4422,  0.4062])
resistance
Saved the embedding for resistance.
['resistant'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2178,  0.1862, -0.6540,  ..., -0.8682, -0.2249,  0.0070])
resistant
Saved the embedding for resistant.
['resist', '##ent'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1988,  0.9181, -0.3333,  ..., -0.3997, -0.3588,  1.0457])
resistent
Saved the embedding for resistent.
['resisting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1237,  0.9236, -0.4994,  ..., -0.1897, -0.5881,  0.8405])
resisting
S

['sad', '##dened'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0262,  0.6265,  0.3351,  ...,  0.2080,  0.3951,  0.7532])
saddened
Saved the embedding for saddened.
['sad', '##istic'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0138,  0.6451,  0.3946,  ...,  0.3908,  0.2973,  0.7125])
sadistic
Saved the embedding for sadistic.
['sadness'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0093,  0.3940,  0.5799,  ...,  0.0998,  0.2555,  0.4305])
sadness
Saved the embedding for sadness.
['sal', '##acious'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([0.2297, 0.3295, 0.0739,  ..., 0.6823, 0.0734, 0.3116])
salacious
Saved the embedding for salacious.
['saliva', '##ting'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.6350,  0.2834,  0.0767,  ..., -0.5616,  0.2566,  0.2964])
salivating
Saved the embeddi

['searching'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1335,  0.0057,  0.0112,  ..., -0.2778,  0.4279,  0.5411])
searching
Saved the embedding for searching.
['secretive'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3127, -0.3362, -0.1284,  ..., -0.2578,  0.2150,  0.1860])
secretive
Saved the embedding for secretive.
['secretive', '##ly'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1245, -0.0758,  0.0838,  ..., -0.0996,  0.3222,  0.4213])
secretively
Saved the embedding for secretively.
['secure'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0189,  0.0635, -0.0660,  ..., -0.3796,  0.3496,  0.7913])
secure
Saved the embedding for secure.
['se', '##date'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0122, -0.3124, -0.4727,  ...,  0.0544,  0.1101,  0.8792])
sedate
Saved the embedding fo

['sick', '##en'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2728,  0.5179,  0.2745,  ..., -0.4409,  0.1305, -0.0965])
sicken
Saved the embedding for sicken.
['sick', '##ened'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1323,  0.5583,  0.1762,  ..., -0.2202,  0.1342, -0.0661])
sickened
Saved the embedding for sickened.
['sigh'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0406,  0.4564,  0.6383,  ..., -0.2941, -0.2850,  0.2434])
sigh
Saved the embedding for sigh.
['silenced'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.5748,  0.8378, -0.5147,  ...,  0.0403, -0.0738,  0.2835])
silenced
Saved the embedding for silenced.
['silent'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.7121,  0.5796, -0.3927,  ..., -0.1244,  0.2935,  0.1680])
silent
Saved the embedding for silent.
['si', '##llin', 

['smooth'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2714, -0.0560, -0.0799,  ...,  0.0659,  0.1826, -0.1712])
smooth
Saved the embedding for smooth.
['smug'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3021, -0.0421,  0.4123,  ...,  0.1663,  0.0923,  0.2920])
smug
Saved the embedding for smug.
['smug', '##ness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([0.2697, 0.0788, 0.4565,  ..., 0.2410, 0.1085, 0.6001])
smugness
Saved the embedding for smugness.
['snake'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.8965,  0.0487, -0.0098,  ...,  0.4522,  0.3907, -0.2765])
snake
Saved the embedding for snake.
['snap', '##py'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4640, -0.6222,  0.2072,  ...,  0.3994,  0.4374, -0.4563])
snappy
Saved the embedding for snappy.
['s', '##nar', '##ky'] has a tok