In [3]:
import sys
import os
from timeit import default_timer as timer
os.getcwd()

'/home/jupyter/Notebooks/crystal/NLP/nlp_testing'

In [ ]:
# Adapted from the tutorial at https://mccormickml.com/2019/05/14/BERT-word-embeddings-tutorial/

In [4]:
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
#logging.basicConfig(level=logging.INFO)

import matplotlib.pyplot as plt
%matplotlib inline

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [7]:
# list(tokenizer.vocab.keys())[5000:5020]
list(tokenizer.vocab.keys())[17733]

'disgusted'

In [ ]:
# Define a new example sentence with multiple meanings of the word "disgusted"
text = "[CLS] She made a disgusted pout [SEP] Her disgusted expression was contagious [SEP]"

# Split the sentence into tokens.
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)

# Map the token strings to their vocabulary indeces.
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

# Display the words with their indeces.
for tup in zip(tokenized_text, indexed_tokens):
    print('{:<12} {:>6,}'.format(tup[0], tup[1]))

In [ ]:
# Recreate vocabulary words from their tokenized representations.
for t in tokenized_text:
    this_word = ''
    for token in t:
        this_word += token.strip('#')
#     print(this_word)

In [ ]:
# Mark each of the tokens as belonging to sentence "0" or "1".

segments_ids = [1] * len(tokenized_text[3])
# segments_ids = [0,0,0]
print (segments_ids)
print(indexed_tokens)
print(tokenized_text[3])

In [ ]:
# Convert inputs to PyTorch tensors
tokens_tensor = torch.tensor([indexed_tokens[3]])
segments_tensors = torch.tensor([segments_ids])

# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-uncased')

# Put the model in "evaluation" mode, meaning feed-forward operation.
model.eval()

In [ ]:
# Predict hidden states features for each layer
with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, segments_tensors)

In [ ]:
print ("Number of layers:", len(encoded_layers))
layer_i = 0

print ("Number of batches:", len(encoded_layers[layer_i]))
batch_i = 0

print ("Number of tokens:", len(encoded_layers[layer_i][batch_i]))
token_i = 1

print ("Number of hidden units:", len(encoded_layers[layer_i][batch_i][token_i]))

In [ ]:
# For our token, select its feature values from layer 5.
token_i = 1
layer_i = 5
vec = encoded_layers[layer_i][batch_i][token_i]
# print(vec)

# Plot the values as a histogram to show their distribution.
plt.figure(figsize=(10,10))
plt.hist(vec, bins=200)
plt.show()

In [ ]:
# `encoded_layers` is a Python list.
print('     Type of encoded_layers: ', type(encoded_layers))

# Each layer in the list is a torch tensor.
print('Tensor shape for each layer: ', encoded_layers[0].size())

In [ ]:
# Concatenate the tensors for all layers. We use `stack` here to
# create a new dimension in the tensor.
token_embeddings = torch.stack(encoded_layers, dim=0)

token_embeddings.size()

In [ ]:
# Remove dimension 1, the "batches".
token_embeddings = torch.squeeze(token_embeddings, dim=1)

token_embeddings.size()

In [ ]:
# Swap dimensions 0 and 1.
token_embeddings = token_embeddings.permute(1,0,2)

token_embeddings.size()

In [23]:
# Concatenate the last 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_last = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_last.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_last), len(token_vecs_cat_last[0])))
print(token_vecs_cat_last[0])

Shape is: 1 x 3072
tensor([-0.2373,  0.8259, -0.6190,  ..., -0.3836, -0.5039,  0.6153])


In [24]:
# Sum the last 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_last = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[-4:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_last.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_last), len(token_vecs_sum_last[0])))

Shape is: 1 x 768


In [ ]:
# Concatenate the first 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_first = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[0], token[1], token[2], token[3]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_first.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_first), len(token_vecs_cat_first[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the first 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_first = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[:4], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_first.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_first), len(token_vecs_sum_first[0])))

In [ ]:
# Concatenate the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_middle1 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[4], token[5], token[6], token[7]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_middle1.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_middle1), len(token_vecs_cat_middle1[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_middle1 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[4:8], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_middle1.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_middle1), len(token_vecs_sum_middle1[0])))

In [ ]:
# Concatenate the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 3,072]
token_vecs_cat_middle2 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[8], token[9], token[10], token[11]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_middle2.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_middle2), len(token_vecs_cat_middle2[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum the middle 4 hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_middle2 = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[8:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_middle2.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_middle2), len(token_vecs_sum_middle2[0])))

In [ ]:
# Concatenate all hidden layers to create word embeddings.
token_vecs_cat_all = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    
    # `token` is a [12 x 768] tensor

    # Concatenate the vectors (that is, append them together) from the last 
    # four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[0], token[1], token[2], token[3], token[4], token[5], token[6], token[7], token[8], token[9], token[10], token[11]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat_all.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat_all), len(token_vecs_cat_all[0])))
print(token_vecs_cat[0])

In [ ]:
# Sum all hidden layers to create word embeddings.
# Stores the token vectors, with shape [22 x 768]
token_vecs_sum_all = []

# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:

    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum_all.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum_all), len(token_vecs_sum_all[0])))

In [ ]:
# Make a single vector to represent the pair of sentences by averaging across tokens.
# `encoded_layers` has shape [12 x 1 x 22 x 768]
sentences_vec = []
# `token_vecs` is a tensor with shape [22 x 768]
token_vecs = encoded_layers[11][0]

# Calculate the average of all 22 token vectors.
sentence_embedding = torch.mean(token_vecs, dim=0)
for s in sentence_embedding:
    sentences_vec.append(s)
print ("Our final sentence embedding vector of shape:", sentence_embedding.size())
print(sentence_embedding[767])
print(sentence_embedding[-1])
print(f'Shape of sentences vector is: {len(sentences_vec)}')
print(sentences_vec[-1])

In [ ]:
from scipy.spatial.distance import cosine
# Test the similarity of a word with itself.
# For words trained contextually, self-synonymy is less than 1.
similarity = 1 - cosine(token_vecs_cat[0], token_vecs_cat[0])
print(f'Similarity of {tokenized_text[8]} and {tokenized_text[8]} in token_vecs_cat is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum[4], token_vecs_sum[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_first[4], token_vecs_cat_first[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_first is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_first[4], token_vecs_sum_first[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_first is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_middle1[4], token_vecs_cat_middle1[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_middle1 is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_middle1[4], token_vecs_sum_middle1[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_middle1 is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_middle2[4], token_vecs_cat_middle2[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_middle2 is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_middle2[4], token_vecs_sum_middle2[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_middle2 is: {similarity}')
# similarity = 1 - cosine(token_vecs_cat_all[4], token_vecs_cat_all[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_cat_all is: {similarity}')
# similarity = 1 - cosine(token_vecs_sum_all[4], token_vecs_sum_all[9])
# print(f'Similarity of {tokenized_text[4]} and {tokenized_text[9]} in token_vecs_sum_all is: {similarity}')

In [6]:
######################################################################################
############## BEGIN TESTING STATIC CONTEXTUAL EMBEDDING CREATION ####################
######################################################################################

In [7]:
def make_vocab(vocab_file):
    # start = timer()
    vocab = []
    # vocab_file = '/home/jupyter/Notebooks/crystal/NLP/MiFace/Python/vocab_files/vocab_checked.txt'
    with open(vocab_file, 'r') as v:
        vocab = v.read().splitlines()
    # end = timer()
    # run_time = end - start
#     print(f'There are {len(vocab)} words in the vocabulary.\n')
#     print(f'It took {run_time} seconds to read the vocabulary file into memory.')
#     print(f'Test word is {vocab[2]}.')
    return vocab

In [8]:
def tokenize_text(vocab):
    tokenized_text = []
    indexed_tokens = []
    for word in vocab:
        # Add the special tokens.
    #     marked_text = "[CLS] " + word + " [SEP]"
        marked_text = word

        # Split the sentence into tokens.
        # tokenized_text = tokenizer.tokenize(marked_text)
        tokenized_text.append(tokenizer.tokenize(marked_text))
#         print(f'Added {tokenized_text[-1]} to the tokenized_text array.')


        # Map the token strings to their vocabulary indeces.
        indexed_tokens.append(tokenizer.convert_tokens_to_ids(tokenized_text[-1]))

        # Display the words with their indeces.
    #     print(f'The word {tokenized_text[-1][1]} is at index {indexed_tokens[-1]}.')
#         for tup in zip(tokenized_text[-1], indexed_tokens[-1]):
#             print('{:<12} {:>6,}'.format(tup[0], tup[1]))
    return tokenized_text, indexed_tokens

In [9]:
def generate_segments_IDs(tokenized_text):
    # Create segment IDs for sentence 1 (there can be a sentence 0 to compare to
    # sentence 1, but we're not doing that).
    # Check that indices and token indices look correct.
    segments_IDs = []
    for i in range(len(tokenized_text)):
        segments_IDs.append([1] * len(tokenized_text[i]))
#     for i in range(len(segments_IDs)):
#         print (segments_IDs[i])
#         print(tokenized_text[i])
    return segments_IDs

In [10]:
def generate_embeddings(indexed_tokens, segments_IDs):
    # Convert inputs to PyTorch tensors
    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_IDs])

    # Load pre-trained model (weights)
    model = BertModel.from_pretrained('bert-base-uncased')

    # Put the model in "evaluation" mode, meaning feed-forward operation.
    model.eval()

    # Predict hidden states features for each layer
    with torch.no_grad():
        encoded_layers, _ = model(tokens_tensor, segments_tensors)
#         print('Type of encoded_layers: ', type(encoded_layers))
        # Each layer in the list is a torch tensor.
#         print('Tensor shape for each layer: ', encoded_layers[0].size())

    # Concatenate the tensors for all layers. We use `stack` here to
    # create a new dimension in the tensor.
    token_embeddings = torch.stack(encoded_layers, dim=0)
#     print(token_embeddings.size())

    # Remove dimension 1, the "batches".
    token_embeddings = torch.squeeze(token_embeddings, dim=1)
#     print(token_embeddings.size())

    # Swap dimensions 0 and 1.
    token_embeddings = token_embeddings.permute(1,0,2)
#     print(token_embeddings.size())
    
    return token_embeddings

In [11]:
def cat_last_four(token_embeddings): 
    # Concatenate the last 4 hidden layers to create contextual embeddings.
    # Stores the token vectors, with shape [22 x 3,072]
    token_vecs_cat_last = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_last.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_last), len(token_vecs_cat_last[0])))
    print(token_vecs_cat_last[0])
    
    return token_vecs_cat_last

In [12]:
def cat_middle_four2(token_embeddings):
    # Concatenate the middle 4 hidden layers to create word embeddings.
    # Stores the token vectors, with shape [22 x 3,072]
    token_vecs_cat_middle2 = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last 
        # four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[8], token[9], token[10], token[11]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_middle2.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_middle2), len(token_vecs_cat_middle2[0])))
    print(token_vecs_cat_middle2[0])
    
    return token_vecs_cat_middle2

In [13]:
def cat_middle_four1(token_embeddings):
    # Concatenate the middle 4 hidden layers to create word embeddings.
    # Stores the token vectors, with shape [22 x 3,072]
    token_vecs_cat_middle1 = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last 
        # four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[4], token[5], token[6], token[7]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_middle1.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_middle1), len(token_vecs_cat_middle1[0])))
    print(token_vecs_cat_middle1[0])
    
    return token_vecs_cat_middle1

In [14]:
def cat_first_four(token_embeddings):
    token_vecs_cat_first = []

    # `token_embeddings` is a [22 x 12 x 768] tensor.

    # For each token in the sentence...
    for token in token_embeddings:

        # `token` is a [12 x 768] tensor

        # Concatenate the vectors (that is, append them together) from the last 
        # four layers.
        # Each layer vector is 768 values, so `cat_vec` is length 3,072.
        cat_vec = torch.cat((token[0], token[1], token[2], token[3]), dim=0)

        # Use `cat_vec` to represent `token`.
        token_vecs_cat_first.append(cat_vec)

    print ('Shape is: %d x %d' % (len(token_vecs_cat_first), len(token_vecs_cat_first[0])))
    print(token_vecs_cat_first[0])
    
    return token_vecs_cat_first

In [15]:
def get_mean_embedding(token_embeddings):
    mean_embedding = sum(token_embeddings) / len(token_embeddings)
    print(mean_embedding)
    
    return mean_embedding

In [16]:
def reconstruct_tokens(tokenized_text):
    vocab_word = ''
    for i in tokenized_text:
        vocab_word += i.strip('#')
    print(vocab_word)

    return vocab_word

In [17]:
def write_embedding(embeddings_file, vocab_word, contextual_embedding):
    try:
        with open(embeddings_file, 'a') as f:
            f.write(vocab_word)
            for value in contextual_embedding[0]:
                f.write(' ' + str(value.item()))
            f.write('\n')
        print(f'Saved the embedding for {vocab_word}.')
    except:
        print('Oh no! Unable to write to the embeddings file.')

In [ ]:
# if __name__ == "__main__":
# Set up input and output paths.
vocab_file = '/home/jupyter/Notebooks/crystal/NLP/MiFace/Python/vocab_files/vocab_checked.txt'
layer_combining_function = cat_middle_four2
embeddings_file = os.path.join('/home/jupyter/Notebooks/crystal/NLP/nlp_testing/embeddings_context_vocab', layer_combining_function.__name__ + '.txt')
if os.path.exists(embeddings_file):
    os.remove(embeddings_file)

    # Create a list of vocabulary words we want embeddings for.
vocab = make_vocab(vocab_file)

# Tokenize the vocabulary and look up the BERT token indices.
tokenized_text, indexed_tokens = tokenize_text(vocab)

# Generate segment IDs for each token.
segments_IDs = generate_segments_IDs(tokenized_text)

# Generate and write out the contextual embeddings for the vocabulary words.
# Embeddings are saved in a standard format that can be used for calcualting
# the cosine distances between word vectors.
for i in range(len(tokenized_text)):
    # Convert indexed tokens and segments to tensors.
    # Create a BERT model for the tokens.
    # Get the encoded model layers and reshape them.
    token_embeddings = generate_embeddings(indexed_tokens[i], segments_IDs[i])
    print(f'{tokenized_text[i]} has a token embedding of size {token_embeddings.size()}')

    # Extract the contextual embedding for a token.
    contextual_embedding = layer_combining_function(token_embeddings)

    # Write the embedding to a text file, with the vocabulary word prepended.
    vocab_word = reconstruct_tokens(tokenized_text[i])
    # Make sure we've got the correct vocabulary word.
    assert vocab[i] == vocab_word
    write_embedding(embeddings_file, vocab[i], contextual_embedding)

['aback'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0913,  1.4276,  0.4738,  ..., -0.4144,  0.0285, -0.0063])
aback
Saved the embedding for aback.
['aba', '##shed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0985, -0.3056, -0.0392,  ...,  0.3008, -0.5077,  0.2036])
abashed
Saved the embedding for abashed.
['ab', '##hor'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.4193,  0.4612,  0.7739,  ..., -0.1391,  0.0203,  0.4971])
abhor
Saved the embedding for abhor.
['ab', '##hor', '##red'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.0553,  0.5331,  0.3810,  ..., -0.1551, -0.0535,  0.1270])
abhorred
Saved the embedding for abhorred.
['ab', '##hor', '##rence'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.1730, -0.8257,  0.6310,  ..., -0.2092,  0.0052,  0.4344])
abhorrence
Saved the embedding 

['ag', '##gra', '##vation'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.0653,  0.8995,  0.5749,  ...,  0.1177,  0.1458, -0.2573])
aggravation
Saved the embedding for aggravation.
['aggression'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5144,  1.0312, -0.6284,  ...,  0.3372, -0.1049, -0.3468])
aggression
Saved the embedding for aggression.
['aggressive'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1463,  0.5762, -0.7487,  ...,  0.3911, -0.5970, -0.5397])
aggressive
Saved the embedding for aggressive.
['ag', '##gr', '##ie', '##ve'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.0470,  0.4448,  0.8178,  ...,  0.1632,  0.1066, -0.7245])
aggrieve
Saved the embedding for aggrieve.
['ag', '##gr', '##ie', '##ved'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.4535,  0.2086,  1.0646,  ..., -0.295

['ang', '##st'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1915,  0.0732,  0.7304,  ...,  0.6035,  0.2142, -0.1650])
angst
Saved the embedding for angst.
['anguish'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0282,  1.4766,  0.3311,  ..., -0.4970,  0.7294, -0.4133])
anguish
Saved the embedding for anguish.
['anguish', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5110,  1.3244,  0.2221,  ..., -0.1738,  0.5002, -0.0183])
anguished
Saved the embedding for anguished.
['animated'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4838,  0.6223,  0.4137,  ...,  0.0671,  0.9273, -0.0550])
animated
Saved the embedding for animated.
['an', '##imo', '##sity'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.7939,  0.5979,  0.1296,  ..., -0.5694, -0.1118,  0.1823])
animosity
Saved the embedding fo

['ashamed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.8249,  0.6267, -0.9373,  ...,  1.0249,  0.1462, -0.2750])
ashamed
Saved the embedding for ashamed.
['aspiring'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.0652,  0.2626, -0.0492,  ...,  0.3584, -0.1985,  0.6254])
aspiring
Saved the embedding for aspiring.
['assert', '##ive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5699,  0.8623,  0.2104,  ...,  0.1907,  0.5752, -0.1986])
assertive
Saved the embedding for assertive.
['assert', '##ively'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.8104,  0.8994,  0.6644,  ..., -0.6660,  0.9689, -0.9693])
assertively
Saved the embedding for assertively.
['assessing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1620,  0.6290, -0.2597,  ...,  0.4135,  0.6680, -0.0492])
assessing
Saved the embedd

['beat'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1441,  1.2114, -0.7565,  ...,  0.5628,  1.0945,  0.3002])
beat
Saved the embedding for beat.
['beaten'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.2069,  0.8025, -0.1612,  ..., -0.1613,  0.3740, -0.8912])
beaten
Saved the embedding for beaten.
['bed', '##ev', '##iled'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.0442,  0.1295,  0.6587,  ..., -0.0631,  0.0515,  0.0749])
bedeviled
Saved the embedding for bedeviled.
['be', '##fu', '##ddled'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0779,  0.1986,  0.8141,  ...,  0.0695,  0.0980, -0.0476])
befuddled
Saved the embedding for befuddled.
['begging'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1176,  1.5832, -1.7210,  ...,  0.7771,  1.2993,  0.1483])
begging
Saved the embedding for beggi

['bleak'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3195,  0.9115,  0.2979,  ..., -0.5004,  0.2403,  0.1353])
bleak
Saved the embedding for bleak.
['b', '##lea', '##ry'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0228,  0.2114,  0.4803,  ...,  0.6304,  0.3375, -0.0791])
bleary
Saved the embedding for bleary.
['blessed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1708,  1.1632,  0.6687,  ..., -0.1502, -0.0342,  0.2539])
blessed
Saved the embedding for blessed.
['blew'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4961,  0.2048,  0.1556,  ...,  0.7316,  0.6114, -0.0876])
blew
Saved the embedding for blew.
['blinded'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2569,  0.9436, -1.4358,  ...,  0.8699,  0.7966, -0.1648])
blinded
Saved the embedding for blinded.
['blinds', '##ided'] has a

['bully'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.6445,  0.6519, -0.5022,  ...,  0.0869, -0.1163, -0.8137])
bully
Saved the embedding for bully.
['bullying'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1923,  0.1629,  0.6417,  ...,  0.4834,  0.3485, -0.0838])
bullying
Saved the embedding for bullying.
['bum', '##med'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.7655,  0.1802,  0.4196,  ...,  0.2805, -0.0769,  0.0932])
bummed
Saved the embedding for bummed.
['bu', '##oya', '##nt'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2820,  0.5009,  0.3915,  ...,  0.1794, -0.1943,  0.1084])
buoyant
Saved the embedding for buoyant.
['burden', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.3671,  0.9289, -0.2373,  ...,  0.2780,  0.4175,  0.2597])
burdened
Saved the embedding for burdened.

['challenged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4743,  0.8378,  0.8892,  ..., -0.7966,  0.0898,  0.3938])
challenged
Saved the embedding for challenged.
['challenging'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.6186,  0.9499, -0.0335,  ...,  0.2596,  0.0946,  0.8002])
challenging
Saved the embedding for challenging.
['chaotic'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.4627,  0.6195, -1.1992,  ...,  0.2740, -0.1896,  0.1575])
chaotic
Saved the embedding for chaotic.
['charged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([0.2144, 0.7838, 0.1377,  ..., 0.6658, 1.6130, 0.2878])
charged
Saved the embedding for charged.
['charm', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1085,  0.1037,  0.3298,  ..., -0.4108,  0.1351,  0.0092])
charmed
Saved the embedding for charmed.

['clue', '##less'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.5456, -0.2245,  0.0973,  ...,  0.2026,  0.0098,  0.1088])
clueless
Saved the embedding for clueless.
['clutched'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.8435,  0.4977, -1.5067,  ...,  0.4988,  1.3342, -0.3034])
clutched
Saved the embedding for clutched.
['cl', '##uttered'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5600,  0.2962, -0.1853,  ..., -0.4170,  0.2542, -0.0473])
cluttered
Saved the embedding for cluttered.
['cock', '##eye', '##d'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2508,  0.7483, -0.3578,  ..., -0.1509, -0.0876, -0.1811])
cockeyed
Saved the embedding for cockeyed.
['cock', '##iness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2752,  0.3661,  0.4629,  ..., -0.3333,  0.0814,  0.6261])
cockiness
Save

Saved the embedding for concentrating.
['concentration'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1136,  1.2601,  0.7379,  ..., -0.5347,  0.4327, -0.1867])
concentration
Saved the embedding for concentration.
['concern'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6477,  0.6747,  0.4007,  ..., -0.1915,  0.0203,  0.0810])
concern
Saved the embedding for concern.
['concerned'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3162,  1.2216,  0.3536,  ...,  0.0479, -0.0382,  0.0238])
concerned
Saved the embedding for concerned.
['con', '##ci', '##lia', '##tory'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.6146,  0.1092,  0.6218,  ...,  0.1498, -0.0593,  0.7261])
conciliatory
Saved the embedding for conciliatory.
['con', '##clusive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5662,  0.8234,

['content'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([0.2950, 0.7161, 0.3305,  ..., 0.0113, 0.0264, 0.5069])
content
Saved the embedding for content.
['content', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0065,  0.3377,  0.4948,  ...,  0.0506,  0.1250,  0.4780])
contented
Saved the embedding for contented.
['contentious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1645,  1.1819, -0.9429,  ...,  0.0278,  0.0344, -0.6342])
contentious
Saved the embedding for contentious.
['content', '##ly'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1971,  0.9866,  0.4541,  ..., -0.2194, -0.0935,  0.1753])
contently
Saved the embedding for contently.
['content', '##ment'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1748,  0.4974,  0.4697,  ...,  0.0829,  0.2005,  0.4189])
contentment
Saved the

['curiosity'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0887,  1.0266, -1.1298,  ...,  0.4343,  0.2771, -0.1912])
curiosity
Saved the embedding for curiosity.
['curious'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0559,  1.3809, -1.9099,  ..., -0.3156,  0.8766, -0.1441])
curious
Saved the embedding for curious.
['cutting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.5306,  0.2506, -0.5993,  ...,  1.2420,  0.3933,  0.6818])
cutting
Saved the embedding for cutting.
['cy', '##nic'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0129,  0.2191,  0.6293,  ..., -0.0789,  0.3549, -0.1174])
cynic
Saved the embedding for cynic.
['cynical'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2753,  0.1263, -0.8167,  ..., -0.8697,  0.4948, -1.1115])
cynical
Saved the embedding for cynical.
['cy', '##nic'

['del', '##ibe', '##rating'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.3813,  0.0335,  0.3423,  ..., -0.1098,  0.2765,  0.8089])
deliberating
Saved the embedding for deliberating.
['delight'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5849,  1.4482, -1.2832,  ...,  1.2346,  0.7432, -0.1954])
delight
Saved the embedding for delight.
['delighted'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.1088,  0.2741, -1.0782,  ...,  0.4620,  0.6261, -0.3548])
delighted
Saved the embedding for delighted.
['delightful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3036,  0.9345,  0.8303,  ..., -0.6799, -0.6274,  0.1997])
delightful
Saved the embedding for delightful.
['del', '##iri', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-1.4626e-01, -4.7090e-01, -9.3705e-04,  ...,  2.7005e-02,
        

['determination'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1605,  0.6582, -0.0027,  ..., -0.3860,  0.5737,  0.5906])
determination
Saved the embedding for determination.
['determined'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6670,  0.0396,  0.6240,  ..., -0.1621,  0.4597,  0.2712])
determined
Saved the embedding for determined.
['determining'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1120,  0.1771,  0.5815,  ...,  0.2044,  0.6191,  0.1602])
determining
Saved the embedding for determining.
['deter', '##red'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.5412,  0.1244,  0.4389,  ..., -0.2651, -0.1264,  0.1172])
deterred
Saved the embedding for deterred.
['det', '##est'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.9375,  0.3597,  0.5620,  ...,  0.2095,  0.5505,  0.1648])
detest
S

['discount', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.4136,  0.2690,  1.1072,  ..., -0.2054,  0.2983, -0.2464])
discounted
Saved the embedding for discounted.
['discouraged'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.1423,  0.7236, -0.1094,  ..., -0.1900,  0.5113, -1.0597])
discouraged
Saved the embedding for discouraged.
['discovery'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.0787,  1.1474, -0.9883,  ...,  0.1296,  0.7135, -0.4367])
discovery
Saved the embedding for discovery.
['disc', '##rim', '##inating'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.4906,  0.4697,  0.4293,  ...,  0.2230,  0.1945,  0.0689])
discriminating
Saved the embedding for discriminating.
['discussed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6686,  0.4457,  0.0229,  ...,  0.3608,  0.2394, -0.

Saved the embedding for disparaging.
['di', '##sp', '##ass', '##ion', '##ate'] has a token embedding of size torch.Size([5, 12, 768])
Shape is: 5 x 3072
tensor([-0.0930, -0.2498,  0.2627,  ..., -0.1241,  0.0627,  0.5590])
dispassionate
Saved the embedding for dispassionate.
['di', '##sp', '##iri', '##ted'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.4464,  0.2442, -0.3300,  ..., -0.1907,  0.3127,  0.8845])
dispirited
Saved the embedding for dispirited.
['di', '##sp', '##iri', '##ted', '##ness'] has a token embedding of size torch.Size([5, 12, 768])
Shape is: 5 x 3072
tensor([ 0.2349, -0.1987,  0.1063,  ..., -0.1098,  0.2353,  0.8494])
dispiritedness
Saved the embedding for dispiritedness.
['di', '##sp', '##lea', '##sed'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.3168, -0.0013,  0.6447,  ..., -0.1515, -0.1264,  0.4032])
displeased
Saved the embedding for displeased.
['displeasure'] has a token embedding 

['do', '##pe', '##y'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.5234,  0.7613, -0.0688,  ...,  0.5572,  0.4042,  0.4795])
dopey
Saved the embedding for dopey.
['dot', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1959,  0.7269, -0.1643,  ..., -0.1431,  0.5493,  0.2836])
doting
Saved the embedding for doting.
['doubt'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3072,  0.3385, -0.8530,  ..., -0.2843,  0.5934, -0.5055])
doubt
Saved the embedding for doubt.
['doubt', '##er'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.3944,  0.1997,  0.3157,  ..., -0.1028,  0.4350, -0.4048])
doubter
Saved the embedding for doubter.
['doubtful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.1359,  0.8346, -0.2823,  ...,  0.1187,  0.7571, -0.2157])
doubtful
Saved the embedding for doubtful.
['doubtf

['eager'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5518,  0.6764, -0.4429,  ..., -0.2509,  0.4406, -0.0296])
eager
Saved the embedding for eager.
['eager', '##ness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0428,  0.2632,  0.7444,  ...,  0.1799, -0.1494,  0.0544])
eagerness
Saved the embedding for eagerness.
['earnest'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3091,  2.1425,  0.6450,  ..., -0.3866,  0.3664,  0.0414])
earnest
Saved the embedding for earnest.
['easy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.0972,  0.6998, -0.2216,  ...,  0.5131,  0.5356,  0.1820])
easy
Saved the embedding for easy.
['e', '##bu', '##llie', '##nt'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([ 0.2494, -0.7355,  0.5511,  ...,  0.0514,  0.5149,  0.6951])
ebullient
Saved the embedding for ebullient.

['eng', '##ross', '##ed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.6183,  0.3337,  0.7556,  ..., -0.0667,  0.1365,  0.0736])
engrossed
Saved the embedding for engrossed.
['eng', '##ross', '##ment'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.1891,  0.8742,  0.5353,  ...,  0.3021,  0.2526,  0.3982])
engrossment
Saved the embedding for engrossment.
['enigma', '##tic'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5502,  0.9316, -0.1192,  ...,  0.2861,  0.1324,  0.7248])
enigmatic
Saved the embedding for enigmatic.
['enjoy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.6445,  0.4551, -0.1728,  ..., -0.3669,  0.6348, -1.2600])
enjoy
Saved the embedding for enjoy.
['enjoying'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4083,  0.6953, -1.3897,  ...,  0.4798,  0.6407, -0.1406])
enjoying
Sav

Saved the embedding for exclamatory.
['exhausted'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.8099,  0.8706, -0.6233,  ..., -0.1941,  0.1398, -0.9543])
exhausted
Saved the embedding for exhausted.
['exhaustion'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3739, -0.0341, -0.0057,  ...,  0.3555,  0.4834, -0.5527])
exhaustion
Saved the embedding for exhaustion.
['exhaust', '##ive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5069,  0.8073, -0.5661,  ..., -0.4066,  1.1156, -1.0086])
exhaustive
Saved the embedding for exhaustive.
['ex', '##hila', '##rated'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.4781, -0.5230,  0.5358,  ..., -0.3106,  0.2888,  0.2869])
exhilarated
Saved the embedding for exhilarated.
['ex', '##hila', '##ration'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0479, -0.49

['feared'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1501,  0.1288,  0.3425,  ..., -0.0146,  0.1106, -0.4962])
feared
Saved the embedding for feared.
['fearful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5452,  0.8712, -0.4757,  ...,  0.2722,  0.2012, -0.0945])
fearful
Saved the embedding for fearful.
['fearing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5610,  0.4636, -0.0186,  ...,  0.2207,  0.0051,  0.1376])
fearing
Saved the embedding for fearing.
['fearless'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.2156,  1.6713,  0.2054,  ..., -0.0249,  0.2052,  1.0902])
fearless
Saved the embedding for fearless.
['fears', '##ome'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.4518,  0.7528, -0.3418,  ..., -0.3023,  0.6629, -0.0212])
fearsome
Saved the embedding for fearsome.
['fe', '##c

['foolish'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.0308,  0.8201, -0.9820,  ..., -0.0695,  0.9513,  0.2258])
foolish
Saved the embedding for foolish.
['for', '##be', '##aring'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.7535, -0.2512,  0.6949,  ..., -0.0350, -0.6964, -0.1669])
forbearing
Saved the embedding for forbearing.
['forbid', '##ding'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2735,  0.6298, -1.0290,  ...,  0.3084,  0.2092,  0.3779])
forbidding
Saved the embedding for forbidding.
['forced'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5998,  0.2714,  0.3786,  ...,  0.8086,  0.3311,  0.3569])
forced
Saved the embedding for forced.
['forceful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.2638,  0.6706,  0.2305,  ..., -0.2790,  0.1487, -0.2512])
forceful
Saved the embeddin

['furrowed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1532,  0.3589,  0.0397,  ..., -0.6101,  0.3727, -0.0563])
furrowed
Saved the embedding for furrowed.
['fur', '##tive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.5498, -0.0429,  0.0174,  ...,  0.1546,  0.8871, -0.1897])
furtive
Saved the embedding for furtive.
['fury'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0528,  1.5857,  0.2010,  ..., -0.3064,  0.4775, -0.1552])
fury
Saved the embedding for fury.
['fuss', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2606,  1.2445, -0.5182,  ...,  0.5664,  0.2463,  0.1482])
fussy
Saved the embedding for fussy.
['gall', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2005,  0.8964, -0.4442,  ...,  0.1267,  0.5849, -0.0285])
galled
Saved the embedding for galled.
['gall', '##ing']

['grateful'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5439,  0.4296, -1.5872,  ...,  0.4198,  0.6978, -0.5881])
grateful
Saved the embedding for grateful.
['gr', '##ati', '##fied'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.3950,  0.8429,  1.0089,  ..., -0.2544,  0.2081,  0.5568])
gratified
Saved the embedding for gratified.
['grave'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5321,  1.3198,  0.8950,  ..., -0.0050,  0.0836,  0.6854])
grave
Saved the embedding for grave.
['great'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.8502e-01,  8.2093e-01,  1.3554e+00,  ..., -9.7020e-02,
         7.1746e-01,  1.2593e-03])
great
Saved the embedding for great.
['greedy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2369,  1.5280, -0.1658,  ...,  0.0921, -0.1741, -0.6235])
greedy
Saved the embe

['hate'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0653,  1.1206, -1.1841,  ...,  0.3572,  0.0322,  0.0620])
hate
Saved the embedding for hate.
['hate', '##ful'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2143,  1.6690, -0.8433,  ..., -0.1749,  0.4242, -0.2195])
hateful
Saved the embedding for hateful.
['hating'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4517,  0.8572, -0.4147,  ..., -0.1127,  0.3792,  0.5469])
hating
Saved the embedding for hating.
['hatred'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0857,  1.1281,  0.4196,  ..., -0.1205,  0.3174,  0.0901])
hatred
Saved the embedding for hatred.
['ha', '##ught', '##y'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.4409,  0.0081,  0.7730,  ..., -0.2836,  0.1957,  0.2670])
haughty
Saved the embedding for haughty.
['haunted'] has a

['hot'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0904,  0.4664, -0.2412,  ..., -0.3534,  0.2074,  0.0857])
hot
Saved the embedding for hot.
['hot', '##shot'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.4799,  0.3302,  0.7781,  ..., -0.2547,  0.2604, -0.0457])
hotshot
Saved the embedding for hotshot.
['huff', '##iness'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.6843,  0.9605,  0.5473,  ..., -0.0785, -0.1712,  0.3303])
huffiness
Saved the embedding for huffiness.
['huff', '##y'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.7372,  0.7603, -0.1738,  ..., -0.1344,  0.2386, -0.3204])
huffy
Saved the embedding for huffy.
['humble'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1018,  1.3629,  0.5269,  ...,  0.1421, -0.0299,  0.4913])
humble
Saved the embedding for humble.
['humble', '##d']

['imp', '##erson', '##al'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.4764,  0.7731,  0.5018,  ..., -0.6992, -0.0931,  0.0955])
impersonal
Saved the embedding for impersonal.
['imp', '##ert', '##inen', '##t'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.1668,  0.5664,  0.9688,  ..., -0.3469, -0.0776,  0.5029])
impertinent
Saved the embedding for impertinent.
['imp', '##ish'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1453,  0.2965,  0.3850,  ..., -0.1747,  0.5154,  0.0557])
impish
Saved the embedding for impish.
['implicated'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0233,  0.7588, -0.0860,  ..., -0.3993,  1.1227, -0.7900])
implicated
Saved the embedding for implicated.
['imp', '##lor', '##ing'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.5167,  0.7561,  0.5459,  ..., -0.4004,  0.

['informal'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4475,  1.3650, -1.5099,  ..., -0.1778,  0.8080,  0.2640])
informal
Saved the embedding for informal.
['informing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1615,  0.3715, -0.3023,  ...,  0.2089,  0.5030,  0.4539])
informing
Saved the embedding for informing.
['in', '##fur', '##iated'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.0552, -0.2578,  0.2040,  ..., -0.0362, -0.0120,  0.1918])
infuriated
Saved the embedding for infuriated.
['inhibit', '##ed'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2269,  1.3959, -0.1157,  ...,  0.1218, -0.2006, -0.0588])
inhibited
Saved the embedding for inhibited.
['inhibit', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2626,  1.2893, -0.7263,  ..., -0.3808, -0.2041, -0.2874])
inhibiting

['interest'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5682,  0.8330, -1.0084,  ...,  0.5243,  0.5465, -0.5630])
interest
Saved the embedding for interest.
['interested'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.8142,  0.6606, -0.9308,  ...,  0.0226, -0.0373, -0.0616])
interested
Saved the embedding for interested.
['inter', '##ject', '##ing'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.7244,  1.8824, -0.5062,  ..., -0.9639,  0.1400,  0.7574])
interjecting
Saved the embedding for interjecting.
['internal', '##izing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.6207,  0.2096, -0.2952,  ...,  0.2161,  0.0993, -0.2791])
internalizing
Saved the embedding for internalizing.
['inter', '##ro', '##gating'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.8082,  0.9366, -0.2887,  ..., -0.5954,

Saved the embedding for jealous.
['je', '##ering'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2414,  0.2001,  0.4985,  ...,  0.3487,  0.2426,  0.6462])
jeering
Saved the embedding for jeering.
['je', '##sti', '##ng'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.5249, -0.1958,  1.0406,  ...,  0.1516,  0.0324,  0.3487])
jesting
Saved the embedding for jesting.
['ji', '##lt', '##ed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-1.0689,  0.8130, -0.0509,  ...,  0.2687,  0.3546,  0.0718])
jilted
Saved the embedding for jilted.
['ji', '##tter', '##y'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.8586,  0.0062,  0.5451,  ...,  0.6116,  0.4328,  0.3247])
jittery
Saved the embedding for jittery.
['jo', '##cular'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4538,  0.0231,  0.2294,  ...,  0.3266,  0

['lazy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1937,  1.3681, -0.0039,  ..., -0.5442,  0.0179,  0.4252])
lazy
Saved the embedding for lazy.
['leaving'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3623,  1.0413, -0.2614,  ...,  0.3761, -0.1400,  0.0926])
leaving
Saved the embedding for leaving.
['le', '##cher', '##ous'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([ 0.2865,  0.1583, -0.0729,  ...,  0.0214,  0.2563, -0.0618])
lecherous
Saved the embedding for lecherous.
['le', '##cturing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0351, -0.6532, -0.1164,  ...,  0.2003,  0.0624,  0.2578])
lecturing
Saved the embedding for lecturing.
['lee', '##ring'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1763,  0.3733,  0.0740,  ...,  0.2444,  0.0860, -0.0250])
leering
Saved the embedding for le

['mel', '##low'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.6693,  0.1115,  0.4886,  ...,  0.1280,  0.0189,  0.3515])
mellow
Saved the embedding for mellow.
['menace'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3942,  0.7986, -0.7077,  ..., -0.3850,  0.0357, -1.0829])
menace
Saved the embedding for menace.
['menacing'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1263,  0.1182, -0.7709,  ...,  0.1566, -0.1225, -0.1189])
menacing
Saved the embedding for menacing.
['mental'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2795,  0.7457, -0.3758,  ...,  0.4618,  0.5648,  0.2464])
mental
Saved the embedding for mental.
['mer', '##rily'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.3415,  0.2911,  0.3215,  ..., -0.0440,  0.4833,  0.3207])
merrily
Saved the embedding for merrily.
['merry'] has 

['mourning'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0969,  1.7599,  0.1182,  ..., -0.0055,  0.3231, -0.0312])
mourning
Saved the embedding for mourning.
['mouthed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0640,  1.6416, -0.5987,  ...,  0.1974,  0.6567,  0.0291])
mouthed
Saved the embedding for mouthed.
['moved'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.3477,  1.4399, -1.5773,  ..., -0.3291,  0.5957,  0.1170])
moved
Saved the embedding for moved.
['mud', '##dled'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.5903,  0.9293,  0.9612,  ..., -0.2270,  0.0139,  0.6110])
muddled
Saved the embedding for muddled.
['mum'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1415, -0.1871,  0.2929,  ..., -0.1809,  0.4981,  0.2543])
mum
Saved the embedding for mum.
['murderous'] has a token emb

['noisy'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2667,  1.5202,  0.2822,  ...,  0.1247,  0.2168,  0.4889])
noisy
Saved the embedding for noisy.
['non', '##bel', '##ie', '##f'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.4292, -0.2421,  0.2782,  ..., -0.4960, -1.1324,  0.1535])
nonbelief
Saved the embedding for nonbelief.
['non', '##chal', '##ance'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.5614,  0.3780,  0.1889,  ..., -0.7230, -0.0551,  0.8250])
nonchalance
Saved the embedding for nonchalance.
['non', '##chal', '##ant'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.8140,  0.4278,  0.1874,  ..., -1.0487,  0.0079,  0.2824])
nonchalant
Saved the embedding for nonchalant.
['non', '##com', '##mit', '##tal'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.7377,  0.6528, -0.4989,  ..., -0.

['orgasm', '##ic'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.5696,  1.4446, -1.1823,  ..., -0.4134, -0.0474, -0.1189])
orgasmic
Saved the embedding for orgasmic.
['or', '##nery'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4271,  1.1348, -0.6695,  ..., -0.2594,  1.2613, -0.1973])
ornery
Saved the embedding for ornery.
['ou', '##ch'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.9488,  0.7390,  0.4891,  ..., -0.1268,  0.3332,  0.5422])
ouch
Saved the embedding for ouch.
['out'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.3877,  0.7306,  0.1990,  ...,  0.1867,  0.6051,  0.0837])
out
Saved the embedding for out.
['outburst'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.2673,  0.6277, -0.1211,  ..., -0.0424,  0.0033, -0.2655])
outburst
Saved the embedding for outburst.
['out', '##cr', '##y

['pep', '##py'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1856, -0.0072, -0.2981,  ...,  0.2813, -0.0095, -0.0204])
peppy
Saved the embedding for peppy.
['per', '##ceptive'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.0955,  0.0580,  0.0962,  ...,  0.2014, -0.0164,  0.3017])
perceptive
Saved the embedding for perceptive.
['per', '##fi', '##dio', '##us'] has a token embedding of size torch.Size([4, 12, 768])
Shape is: 4 x 3072
tensor([-0.5450, -0.1752, -0.4489,  ...,  0.4385,  0.0344,  0.0186])
perfidious
Saved the embedding for perfidious.
['per', '##ky'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.6733, -0.4477, -0.1192,  ...,  0.3323,  0.1037,  0.3684])
perky
Saved the embedding for perky.
['per', '##plex', '##ed'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.4627, -0.0200, -0.1296,  ...,  0.3654, -0.0192,  0.8681])
perpl

['pleasure'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0231,  0.6162, -0.4066,  ..., -0.3462,  0.2983,  0.1029])
pleasure
Saved the embedding for pleasure.
['pleasure', '##d'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.4880,  0.2823,  0.0591,  ..., -0.3380,  0.3149, -0.0183])
pleasured
Saved the embedding for pleasured.
['pl', '##ian', '##t'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.2164, -0.2489,  1.0135,  ...,  0.3666,  0.2144,  0.4185])
pliant
Saved the embedding for pliant.
['plotting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5518,  1.0190, -0.5127,  ...,  0.4126,  0.8506, -0.7856])
plotting
Saved the embedding for plotting.
['po', '##ignant'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.4140, -0.0944,  0.4332,  ...,  0.0613, -0.0804,  0.3813])
poignant
Saved the embeddin

Saved the embedding for provoked.
['pro', '##voking'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-1.4477,  0.1996,  0.2587,  ..., -0.5888,  0.4777, -0.0522])
provoking
Saved the embedding for provoking.
['pry', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.8466,  0.6227, -0.9438,  ...,  0.5916,  1.1478, -0.6731])
prying
Saved the embedding for prying.
['psycho'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5909, -0.1195,  0.0130,  ...,  0.6649,  0.4294, -0.0734])
psycho
Saved the embedding for psycho.
['psychotic'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1226, -0.2172, -0.1510,  ...,  0.0042,  0.2293, -0.5207])
psychotic
Saved the embedding for psychotic.
['puck', '##ish'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1048, -0.2176, -0.0958,  ...,  0.4725,  0.4016,  0.5269])
puc

['ravi', '##ng'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2081,  0.8138,  0.4301,  ..., -0.4530,  0.1694, -0.3045])
raving
Saved the embedding for raving.
['reactive'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.9106,  1.0395,  0.7150,  ..., -0.6414,  0.5375,  0.2730])
reactive
Saved the embedding for reactive.
['ready'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5413,  0.5083, -0.1867,  ...,  0.4113,  0.1582,  0.1823])
ready
Saved the embedding for ready.
['realization'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.0916,  1.5609, -0.1275,  ..., -0.1455,  0.4877, -0.0803])
realization
Saved the embedding for realization.
['reassured'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.4392,  1.6080, -1.0795,  ...,  0.7814,  0.3198,  0.3505])
reassured
Saved the embedding for reassured.
['

['res', '##ent'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.8119,  0.7059,  0.4224,  ...,  0.5156,  0.3991,  0.3232])
resent
Saved the embedding for resent.
['res', '##ent', '##ful'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.4961,  0.6787,  1.1469,  ..., -0.0020, -0.2213,  0.2547])
resentful
Saved the embedding for resentful.
['res', '##enting'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.0850,  0.7135,  1.1565,  ...,  0.0873, -0.2477, -0.4359])
resenting
Saved the embedding for resenting.
['resentment'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.1651,  0.3080, -0.6607,  ..., -0.3694,  0.1074, -0.3617])
resentment
Saved the embedding for resentment.
['reserved'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.9024,  0.1464, -0.2234,  ...,  0.4444,  0.6599, -0.1958])
reserved
Saved the

['rude'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2743,  1.4921, -1.3118,  ...,  0.6078,  0.0542,  0.3155])
rude
Saved the embedding for rude.
['rue', '##ful'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.1947,  0.0231, -0.4452,  ..., -0.1316,  0.2934, -0.5996])
rueful
Saved the embedding for rueful.
['ru', '##ffled'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([ 0.2122, -0.2337,  0.2148,  ...,  0.1517, -0.0937,  0.1688])
ruffled
Saved the embedding for ruffled.
['rum', '##inating'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.6920,  0.6397, -0.2072,  ...,  0.7198,  0.3160,  0.3517])
ruminating
Saved the embedding for ruminating.
['rust', '##led'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1814,  1.0177,  0.4662,  ..., -0.1460,  0.3409, -0.2930])
rustled
Saved the embedding for rustled.

['sc', '##orn', '##ful'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.6392,  0.6409,  0.6498,  ...,  0.3199, -0.0337,  0.1653])
scornful
Saved the embedding for scornful.
['scowl'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4755,  1.5118, -0.2807,  ..., -0.9004,  0.5228, -0.3453])
scowl
Saved the embedding for scowl.
['scowl', '##ing'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.2111,  1.2100,  0.0470,  ..., -0.1680,  0.5137,  0.0280])
scowling
Saved the embedding for scowling.
['scream'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([0.2164, 0.6354, 0.0186,  ..., 0.0978, 0.3162, 0.3296])
scream
Saved the embedding for scream.
['screaming'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.0957,  0.5750, -0.0155,  ...,  0.2512,  0.4541,  0.3795])
screaming
Saved the embedding for screaming.
['sc'

['shocking', '##ly'] has a token embedding of size torch.Size([2, 12, 768])
Shape is: 2 x 3072
tensor([-0.1134,  1.5751, -0.3316,  ...,  0.5579,  0.5694, -0.3242])
shockingly
Saved the embedding for shockingly.
['shook'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2943,  0.8700, -1.8979,  ...,  0.4321,  1.0311, -0.5007])
shook
Saved the embedding for shook.
['shout'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([ 0.2155,  0.7258,  0.0052,  ...,  0.4876,  1.2998, -0.5576])
shout
Saved the embedding for shout.
['shouting'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.1856,  1.2181, -0.4316,  ...,  0.0904,  0.3564,  0.6262])
shouting
Saved the embedding for shouting.
['sh', '##rew', '##d'] has a token embedding of size torch.Size([3, 12, 768])
Shape is: 3 x 3072
tensor([-0.0278,  0.4411,  0.4081,  ..., -0.1615,  0.1131, -0.4956])
shrewd
Saved the embedding for shrewd.
['shy

['smashed'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.2279,  0.5602, -0.1967,  ...,  0.1943,  1.4270, -0.0475])
smashed
Saved the embedding for smashed.
['smile'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-1.2074,  0.2163,  0.1038,  ...,  0.8780,  0.2743,  0.2939])
smile
Saved the embedding for smile.
['smiley'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.5748, -0.6122, -0.2743,  ...,  0.4419, -0.3123,  0.1988])
smiley
Saved the embedding for smiley.
['smiling'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4768,  0.6892, -1.1503,  ...,  0.4351,  0.4747, -0.0259])
smiling
Saved the embedding for smiling.
['smirk'] has a token embedding of size torch.Size([1, 12, 768])
Shape is: 1 x 3072
tensor([-0.4651,  1.0724, -0.6079,  ..., -0.8278,  0.1095, -0.8049])
smirk
Saved the embedding for smirk.
['smirk', '##ing'] has a token embe